type Option = { label: string; value: unknown };
type Source = {
  path: string;
  label: string;
  value: string;
  multiple?: boolean;
  dependsOn?: string;
  pathsByValue?: Record<string, string>;
  serialize?: "json" | "array";
};
export type ResourceProps = {
  title: string;
  desc: string;
  apiPath: string;
  fields: string[];
  labels: Record<string, string>;
  requiredFields?: string[];
  numberFields?: string[];
  readonly?: boolean;
  allowCreate?: boolean;
  allowEdit?: boolean;
  editableFields?: string[];
  updateKey?: string;
  updateMethod?: "put" | "patch";
  fieldOptions?: Record<string, Option[]>;
  optionSources?: Record<string, Source>;
  fieldTypes?: Record<string, string>;
  statePath?: string;
  stateLabel?: string;
  stateMethod?: "post" | "patch";
  builtinActions?: string[];
  builtinActionMap?: Record<string, string>;
  relatedFields?: string[];
  actionForms?: Record<
    string,
    {
      fields: string[];
      labels: Record<string, string>;
      requiredFields?: string[];
      fieldOptions?: Record<string, Option[]>;
      fieldTypes?: Record<string, string>;
      rowFields?: Record<string, string>;
    }
  >;
  relatedLabels?: Record<string, string>;
  exportPath?: string;
  emptyTitle?: string;
  emptyDescription?: string;
  detailSections?: Array<{
    title: string;
    path: string;
    fields: string[];
    labels: Record<string, string>;
  }>;
  defaultFormValues?: Record<string, unknown>;
};

const opts = (values: [string, unknown][]) =>
  values.map(([label, value]) => ({ label, value }));
const status = opts([
  ["草稿", "DRAFT"],
  ["待审核", "PENDING_REVIEW"],
  ["已批准", "APPROVED"],
  ["启用", "ACTIVE"],
  ["暂停", "SUSPENDED"],
  ["已完成", "COMPLETED"],
  ["失败", "FAILED"],
  ["退役", "RETIRED"],
]);
const yesNo = opts([
  ["是", true],
  ["否", false],
]);
const channelSource = {
  path: "/api/provider-instances",
  label: "instanceName",
  value: "id",
};
const tenantSource = { path: "/api/tenants", label: "name", value: "id" };
const statementNow = new Date(),
  statementFrom = new Date(
    Date.UTC(statementNow.getUTCFullYear(), statementNow.getUTCMonth(), 1),
  ).toISOString(),
  statementTo = new Date(
    Date.UTC(statementNow.getUTCFullYear(), statementNow.getUTCMonth() + 1, 1),
  ).toISOString();

export const resources: Record<string, ResourceProps> = {
  providerTemplates: {
    title: "供应商模板",
    desc: "独立维护供应商协议、鉴权方式与模型目录模板。",
    apiPath: "/api/provider-templates",
    fields: [
      "providerName",
      "providerType",
      "protocol",
      "defaultApiBase",
      "authType",
      "status",
    ],
    labels: {
      providerName: "供应商名称",
      providerType: "供应商类型",
      protocol: "协议",
      defaultApiBase: "默认 API 地址",
      authType: "鉴权方式",
      status: "状态",
    },
    requiredFields: [
      "providerName",
      "providerType",
      "protocol",
      "defaultApiBase",
      "authType",
    ],
    updateMethod: "patch",
    fieldOptions: {
      protocol: opts([
        ["开放接口兼容", "openai_compatible"],
        ["微软云协议", "azure"],
        ["安索匹克协议", "anthropic"],
        ["谷歌双子座协议", "gemini"],
        ["本地推理协议", "vllm"],
      ]),
      authType: opts([
        ["Bearer 密钥", "BEARER"],
        ["API Key 请求头", "API_KEY_HEADER"],
        ["无需鉴权", "NONE"],
      ]),
      status,
    },
    fieldTypes: { protocol: "select", authType: "select", status: "select" },
    builtinActions: ["启用为渠道", "复制", "查看模型"],
    builtinActionMap: {
      启用为渠道: ":id/enable",
      复制: ":id/copy",
      查看模型: "GET :id/model-templates",
    },
    actionForms: {
      启用为渠道: {
        fields: ["instanceName", "apiBase", "region", "environment", "owner"],
        labels: {
          instanceName: "渠道名称",
          apiBase: "API 地址",
          region: "区域",
          environment: "环境",
          owner: "负责人",
        },
        requiredFields: ["instanceName", "apiBase"],
        fieldOptions: {
          region: opts([
            ["中国", "CN"],
            ["日本", "JP"],
            ["美国", "US"],
            ["欧洲", "EU"],
          ]),
          environment: opts([
            ["开发", "开发"],
            ["测试", "测试"],
            ["生产", "生产"],
          ]),
        },
      },
    },
    relatedFields: [
      "providerModelName",
      "defaultDisplayName",
      "supportedEndpoints",
      "status",
    ],
  },
  providerChannels: {
    title: "供应商渠道",
    desc: "承载真实连接、密钥、区域、限流与模型发现。",
    apiPath: "/api/provider-instances",
    fields: [
      "instanceName",
      "providerTemplateId",
      "apiStyle",
      "apiBase",
      "region",
      "environment",
      "owner",
      "rateLimitRpm",
      "rateLimitTpm",
      "keyStatus",
      "healthStatus",
      "status",
    ],
    labels: {
      instanceName: "渠道名称",
      providerTemplateId: "供应商模板",
      apiStyle: "协议",
      apiBase: "API 地址",
      region: "区域",
      environment: "环境",
      owner: "负责人",
      rateLimitRpm: "每分钟请求",
      rateLimitTpm: "每分钟 Token",
      keyStatus: "密钥状态",
      healthStatus: "健康状态",
      status: "状态",
    },
    requiredFields: [
      "instanceName",
      "providerTemplateId",
      "apiStyle",
      "apiBase",
    ],
    numberFields: ["rateLimitRpm", "rateLimitTpm"],
    optionSources: {
      providerTemplateId: {
        path: "/api/provider-templates",
        label: "providerName",
        value: "id",
      },
    },
    fieldOptions: {
      apiStyle: opts([
        ["开放接口兼容", "openai_compatible"],
        ["微软云协议", "azure"],
        ["安索匹克协议", "anthropic"],
        ["谷歌双子座协议", "gemini"],
        ["本地推理协议", "vllm"],
      ]),
      region: opts([
        ["中国", "CN"],
        ["日本", "JP"],
        ["美国", "US"],
        ["欧洲", "EU"],
      ]),
      environment: opts([
        ["开发", "开发"],
        ["测试", "测试"],
        ["生产", "生产"],
      ]),
      status: opts([
        ["启用", "启用"],
        ["暂停", "暂停"],
        ["停用", "停用"],
      ]),
    },
    fieldTypes: {
      apiStyle: "select",
      region: "select",
      environment: "select",
      status: "select",
    },
    statePath: "status",
    builtinActions: ["连接测试", "发现模型", "托管或轮换密钥"],
    builtinActionMap: {
      连接测试: ":id/test-connection",
      发现模型: ":id/discover-models",
      托管或轮换密钥: "POST /api/provider-secrets",
    },
    actionForms: {
      托管或轮换密钥: {
        fields: ["secretName", "secretValue"],
        labels: { secretName: "密钥名称", secretValue: "密钥值" },
        requiredFields: ["secretValue"],
        fieldTypes: { secretValue: "password" },
        rowFields: { providerInstanceId: "id" },
      },
    },
  },
  modelReferences: {
    title: "公共模型参考库",
    desc: "展示有来源、可信度和快照依据的公共模型元数据。",
    apiPath: "/api/model-references",
    fields: [
      "canonicalName",
      "displayName",
      "vendor",
      "family",
      "capabilityClaims",
      "contextLength",
      "sourceType",
      "sourceRef",
      "sourceConfidence",
      "status",
      "version",
      "updatedAt",
    ],
    labels: {
      canonicalName: "模型标识",
      displayName: "展示名称",
      vendor: "供应商",
      family: "模型家族",
      capabilityClaims: "能力声明",
      contextLength: "上下文窗口",
      sourceType: "来源类型",
      sourceRef: "来源依据",
      sourceConfidence: "可信度",
      status: "状态",
      version: "版本",
      updatedAt: "更新时间",
    },
    requiredFields: ["canonicalName", "displayName", "sourceType"],
    numberFields: ["contextLength", "sourceConfidence"],
    allowEdit: false,
    optionSources: {
      capabilityClaims: {
        path: "/api/model-capability-tags",
        label: "displayName",
        value: "code",
        multiple: true,
        serialize: "array",
      },
    },
    fieldOptions: {
      sourceType: opts([
        ["供应商接口", "PROVIDER_API"],
        ["公共参考来源", "PUBLIC_REFERENCE"],
        ["文件导入", "FILE_IMPORT"],
      ]),
      status,
    },
    fieldTypes: { capabilityClaims: "multiselect", sourceType: "select" },
    emptyTitle: "尚无公共模型参考数据",
    emptyDescription: "同步任务产生并审核的数据会显示在这里。",
  },
  modelDeployments: {
    title: "模型部署",
    desc: "审核渠道发现的真实模型部署并控制其可路由资格。",
    apiPath: "/api/channel-model-deployments",
    readonly: true,
    fields: [
      "providerInstanceId",
      "instanceName",
      "providerModelName",
      "displayName",
      "publicModelReferenceId",
      "reviewStatus",
      "routingStatus",
      "priceStatus",
      "priceMatchType",
      "firstSeenAt",
      "lastSeenAt",
      "missingAt",
      "version",
    ],
    labels: {
      providerInstanceId: "供应商渠道",
      instanceName: "渠道名称",
      providerModelName: "渠道模型名",
      displayName: "展示名称",
      publicModelReferenceId: "公共模型参考",
      reviewStatus: "审核状态",
      routingStatus: "路由资格",
      priceStatus: "价格状态",
      priceMatchType: "价格匹配",
      firstSeenAt: "首次发现",
      lastSeenAt: "最后发现",
      missingAt: "消失时间",
      version: "版本",
    },
    optionSources: { providerInstanceId: channelSource },
    fieldOptions: {
      priceStatus: opts([
        ["已匹配", "MATCHED"],
        ["缺少价格", "MISSING"],
      ]),
      priceMatchType: opts([
        ["精确匹配", "EXACT"],
        ["别名匹配", "ALIAS"],
        ["人工匹配", "MANUAL"],
      ]),
    },
    fieldTypes: { providerInstanceId: "select" },
    builtinActions: ["审核通过", "驳回"],
    builtinActionMap: {
      审核通过: "PATCH :id/review?decision=APPROVE",
      驳回: "PATCH :id/review?decision=REJECT",
    },
  },
  serviceModels: {
    title: "企业服务模型",
    desc: "向业务方发布稳定别名，并绑定已审核部署和路由策略；成本由部署模型自动匹配供应商官方价格。",
    apiPath: "/api/platform-models",
    fields: [
      "platformModelName",
      "displayName",
      "providerInstanceIds",
      "actualModels",
      "routePolicyId",
      "visibilityScope",
      "approvalRequired",
      "status",
    ],
    labels: {
      platformModelName: "服务模型名",
      displayName: "展示名称",
      providerInstanceIds: "供应商渠道",
      actualModels: "已审核部署模型",
      routePolicyId: "路由策略",
      visibilityScope: "可见范围",
      approvalRequired: "需要审批",
      status: "状态",
    },
    requiredFields: [
      "platformModelName",
      "displayName",
      "providerInstanceIds",
      "actualModels",
      "routePolicyId",
      "visibilityScope",
    ],
    optionSources: {
      providerInstanceIds: { ...channelSource, multiple: true },
      actualModels: {
        path: "/api/channel-model-deployments",
        label: "providerModelName",
        value: "providerModelName",
        multiple: true,
      },
      routePolicyId: { path: "/api/routes", label: "name", value: "id" },
      visibilityScope: { ...tenantSource, multiple: true },
    },
    fieldOptions: {
      visibilityScope: opts([
        ["全部租户", "全部租户"],
        ["内部租户", "内部租户"],
      ]),
      approvalRequired: yesNo,
      status,
    },
    fieldTypes: {
      providerInstanceIds: "multiselect",
      actualModels: "multiselect",
      routePolicyId: "select",
      visibilityScope: "multiselect",
      approvalRequired: "select",
    },
    builtinActions: ["提交审批", "发布"],
    builtinActionMap: { 提交审批: ":id/submit", 发布: "PATCH :id/publish" },
  },
  capabilityValidations: {
    title: "能力验证",
    desc: "从模型部署发起服务端真实探测并下钻验证证据。",
    apiPath: "/api/channel-model-deployments",
    readonly: true,
    fields: [
      "providerInstanceId",
      "instanceName",
      "providerModelName",
      "displayName",
      "reviewStatus",
      "routingStatus",
      "lastSeenAt",
    ],
    labels: {
      providerInstanceId: "供应商渠道",
      instanceName: "渠道名称",
      providerModelName: "渠道模型",
      displayName: "展示名称",
      reviewStatus: "审核状态",
      routingStatus: "路由资格",
      lastSeenAt: "最后发现",
    },
    optionSources: {
      deploymentId: {
        path: "/api/channel-model-deployments",
        label: "providerModelName",
        value: "id",
      },
      providerInstanceId: channelSource,
    },
    builtinActions: ["发起探测", "验证记录"],
    builtinActionMap: {
      发起探测: ":id/probe",
      验证记录: "GET :id/capability-validations",
    },
    actionForms: {
      发起探测: {
        fields: ["capabilityCode"],
        labels: { capabilityCode: "探测能力" },
        requiredFields: ["capabilityCode"],
        fieldOptions: {
          capabilityCode: opts([
            ["对话", "CHAT"],
            ["流式对话", "STREAM"],
            ["向量嵌入", "EMBEDDING"],
          ]),
        },
      },
    },
    relatedFields: [
      "capabilityCode",
      "testType",
      "status",
      "evidenceRef",
      "latencyMs",
      "validatedAt",
    ],
  },
  dataSources: {
    title: "数据源管理",
    desc: "管理模型目录、公开资料和价格来源，不直接覆盖生产配置。",
    apiPath: "/api/data-sources",
    allowEdit: false,
    fields: [
      "name",
      "sourceType",
      "endpoint",
      "providerInstanceId",
      "authRef",
      "syncMode",
      "scheduleExpression",
      "nextRunAt",
      "lastSyncAt",
      "lastSyncStatus",
      "status",
      "createdAt",
    ],
    labels: {
      name: "数据源名称",
      sourceType: "来源类型",
      endpoint: "来源地址",
      providerInstanceId: "供应商渠道",
      authRef: "密钥引用",
      config: "受控导入配置",
      syncMode: "同步方式",
      scheduleExpression: "同步周期",
      nextRunAt: "下次执行时间",
      lastSyncAt: "最近同步时间",
      lastSyncStatus: "最近同步状态",
      status: "状态",
      createdAt: "创建时间",
    },
    requiredFields: ["name", "sourceType", "syncMode"],
    editableFields: [
      "name",
      "sourceType",
      "endpoint",
      "providerInstanceId",
      "authRef",
      "config",
      "syncMode",
      "scheduleExpression",
    ],
    optionSources: { providerInstanceId: channelSource },
    fieldOptions: {
      sourceType: opts([
        ["供应商接口", "PROVIDER_API"],
        ["公共参考来源", "PUBLIC_REFERENCE"],
        ["受控文件导入", "FILE_IMPORT"],
      ]),
      syncMode: opts([
        ["手动", "MANUAL"],
        ["定时", "SCHEDULED"],
      ]),
      scheduleExpression: opts([
        ["每十五分钟", "PT15M"],
        ["每小时", "PT1H"],
        ["每六小时", "PT6H"],
        ["每天", "P1D"],
        ["每周", "P7D"],
      ]),
      status,
    },
    fieldTypes: {
      sourceType: "select",
      providerInstanceId: "select",
      config: "json",
      syncMode: "select",
      scheduleExpression: "select",
      status: "select",
    },
    builtinActions: ["立即同步"],
    builtinActionMap: { 立即同步: ":id/sync" },
  },
  syncJobs: {
    title: "同步任务",
    desc: "查看真实同步执行、原始快照、差异数量与失败原因。",
    apiPath: "/api/sync-jobs",
    readonly: true,
    fields: [
      "dataSourceId",
      "jobType",
      "triggerType",
      "status",
      "cursorValue",
      "recordsRead",
      "recordsChanged",
      "errorCode",
      "errorMessage",
      "startedAt",
      "completedAt",
      "createdAt",
    ],
    labels: {
      dataSourceId: "数据源",
      jobType: "任务类型",
      triggerType: "触发方式",
      status: "状态",
      cursorValue: "同步游标",
      recordsRead: "读取记录",
      recordsChanged: "变更记录",
      errorCode: "错误码",
      errorMessage: "错误信息",
      startedAt: "开始时间",
      completedAt: "完成时间",
      createdAt: "创建时间",
    },
    optionSources: {
      dataSourceId: { path: "/api/data-sources", label: "name", value: "id" },
    },
  },
  modelDiscoveries: {
    title: "模型发现",
    desc: "按渠道查看原始模型快照及采集依据。",
    apiPath: "/api/provider-instances",
    readonly: true,
    fields: [
      "instanceName",
      "apiBase",
      "region",
      "lastConnectionTestAt",
      "healthStatus",
      "status",
    ],
    labels: {
      instanceName: "供应商渠道",
      apiBase: "来源地址",
      region: "区域",
      lastConnectionTestAt: "连接测试时间",
      healthStatus: "健康状态",
      status: "状态",
    },
    builtinActions: ["查看快照", "发现模型"],
    builtinActionMap: {
      查看快照: "GET :id/model-snapshots",
      发现模型: ":id/discover-models",
    },
    relatedFields: [
      "sourceEndpoint",
      "httpStatus",
      "checksum",
      "discoveredAt",
      "createdAt",
    ],
  },
  discoveryDiffs: {
    title: "差异审核",
    desc: "对比旧值、新值、来源和影响范围后作出可审计决策。",
    apiPath: "/api/discovery-diffs",
    readonly: true,
    fields: [
      "providerInstanceId",
      "providerModelName",
      "deploymentId",
      "snapshotId",
      "fieldName",
      "oldValue",
      "newValue",
      "source",
      "confidence",
      "decision",
      "decisionReason",
      "decidedBy",
      "decidedAt",
    ],
    labels: {
      providerInstanceId: "供应商渠道",
      providerModelName: "渠道模型",
      deploymentId: "模型部署",
      snapshotId: "原始快照",
      fieldName: "字段",
      oldValue: "旧值",
      newValue: "新值",
      source: "来源",
      confidence: "可信度",
      decision: "审核决定",
      decisionReason: "审核理由",
      decidedBy: "审核人",
      decidedAt: "审核时间",
    },
    builtinActions: ["接受", "忽略", "固定", "回滚"],
    builtinActionMap: {
      接受: "PATCH :id/decision?decision=ACCEPTED",
      忽略: "PATCH :id/decision?decision=IGNORED",
      固定: "PATCH :id/decision?decision=PINNED",
      回滚: ":id/rollback",
    },
  },
  publicPriceReferences: {
    title: "公共价格参考",
    desc: "展示 LiteLLM、models.dev 等公共目录的独立参考价格，仅用于交叉核验，不直接参与生产计费。",
    apiPath: "/api/public-price-references",
    readonly: true,
    fields: [
      "sourceName",
      "adapterCode",
      "providerType",
      "providerModelName",
      "displayName",
      "currency",
      "region",
      "requestMode",
      "inputAmountPer1k",
      "outputAmountPer1k",
      "sourceRef",
      "evidenceHash",
      "status",
      "observedAt",
    ],
    labels: {
      sourceName: "参考来源",
      adapterCode: "适配器",
      providerType: "供应商",
      providerModelName: "模型标识",
      displayName: "模型名称",
      currency: "币种",
      region: "区域",
      requestMode: "调用模式",
      serviceTier: "服务层级",
      contextTier: "上下文阶梯",
      inputAmountPer1k: "输入金额/千 Token",
      outputAmountPer1k: "输出金额/千 Token",
      priceComponents: "完整价格组件",
      sourceRef: "来源依据",
      evidenceHash: "证据哈希",
      status: "状态",
      observedAt: "最近观测时间",
    },
    fieldOptions: {
      status: opts([
        ["有效", "ACTIVE"],
        ["来源中缺失", "MISSING"],
        ["存在争议", "DISPUTED"],
      ]),
    },
    builtinActions: ["查看价格组件"],
    builtinActionMap: { 查看价格组件: "GET :id" },
    relatedFields: ["priceComponents", "sourceRef", "evidenceHash", "serviceTier", "contextTier"],
    emptyTitle: "尚无公共价格参考",
    emptyDescription: "请在价格源管理中启用 LiteLLM 或 models.dev 参考源并执行同步。",
  },
  providerPriceSources: {
    title: "价格源管理",
    desc: "配置公共参考源与供应商官方价格源，自动获取原始价格并按规则更新。",
    apiPath: "/api/provider-price-sources",
    fields: [
      "name",
      "sourceClass",
      "adapterCode",
      "providerType",
      "authMode",
      "providerInstanceId",
      "endpoint",
      "region",
      "defaultCurrency",
      "scheduleExpression",
      "autoPublish",
      "maxAutoChangeRatio",
      "confirmationRuns",
      "status",
      "lastSuccessAt",
      "lastFailureAt",
      "lastError",
      "pendingDiffCount",
      "updatedAt",
    ],
    labels: {
      name: "价格源名称",
      sourceClass: "价格源类别",
      adapterCode: "适配器",
      providerType: "供应商类型",
      authMode: "认证方式",
      providerInstanceId: "认证供应商渠道",
      endpoint: "官方来源地址",
      officialHosts: "官方域名",
      region: "价格区域",
      defaultCurrency: "默认币种",
      scheduleExpression: "同步周期",
      autoPublish: "低风险自动发布",
      maxAutoChangeRatio: "最大自动变动比例",
      confirmationRuns: "连续确认次数",
      config: "适配器配置",
      status: "状态",
      lastSuccessAt: "最近成功时间",
      lastFailureAt: "最近失败时间",
      lastError: "最近错误",
      pendingDiffCount: "待审核差异",
      updatedAt: "更新时间",
    },
    requiredFields: [
      "name",
      "sourceClass",
      "adapterCode",
      "authMode",
      "endpoint",
      "officialHosts",
      "region",
      "defaultCurrency",
      "scheduleExpression",
      "maxAutoChangeRatio",
      "confirmationRuns",
      "status",
    ],
    editableFields: [
      "name",
      "sourceClass",
      "adapterCode",
      "providerType",
      "authMode",
      "providerInstanceId",
      "endpoint",
      "officialHosts",
      "region",
      "defaultCurrency",
      "scheduleExpression",
      "autoPublish",
      "maxAutoChangeRatio",
      "confirmationRuns",
      "config",
      "status",
    ],
    updateMethod: "patch",
    numberFields: ["maxAutoChangeRatio", "confirmationRuns", "pendingDiffCount"],
    optionSources: {
      providerType: {
        path: "/api/provider-templates",
        label: "providerName",
        value: "providerType",
      },
      providerInstanceId: {
        path: "/api/provider-instances",
        label: "instanceName",
        value: "id",
      },
    },
    fieldOptions: {
      sourceClass: opts([
        ["公共参考来源", "PUBLIC_REFERENCE"],
        ["供应商官方价格", "OFFICIAL"],
      ]),
      adapterCode: opts([
        ["LiteLLM 成本参考表", "LITELLM_COST_MAP"],
        ["models.dev 公共参考", "MODELS_DEV"],
        ["DeepSeek 官方价格页", "DEEPSEEK_OFFICIAL_PAGE"],
        ["供应商官方 JSON", "OFFICIAL_JSON"],
        ["供应商官方 CSV", "OFFICIAL_CSV"],
      ]),
      authMode: opts([
        ["无需认证", "NONE"],
        ["复用供应商渠道凭据", "PROVIDER_INSTANCE"],
      ]),
      region: opts([
        ["全球", "global"],
        ["中国", "cn"],
        ["美国", "us"],
        ["欧洲", "eu"],
        ["亚太", "apac"],
      ]),
      defaultCurrency: opts([
        ["人民币", "CNY"],
        ["美元", "USD"],
        ["欧元", "EUR"],
      ]),
      scheduleExpression: opts([
        ["每十五分钟", "PT15M"],
        ["每小时", "PT1H"],
        ["每六小时", "PT6H"],
        ["每天", "P1D"],
        ["每周", "P7D"],
      ]),
      autoPublish: yesNo,
      status: opts([
        ["草稿", "DRAFT"],
        ["启用", "ACTIVE"],
        ["暂停", "PAUSED"],
        ["异常", "DEGRADED"],
        ["停用", "DISABLED"],
      ]),
    },
    fieldTypes: {
      sourceClass: "select",
      adapterCode: "select",
      providerType: "select",
      authMode: "select",
      providerInstanceId: "select",
      officialHosts: "json",
      region: "select",
      defaultCurrency: "select",
      scheduleExpression: "select",
      autoPublish: "select",
      config: "json",
      status: "select",
    },
    defaultFormValues: {
      sourceClass: "PUBLIC_REFERENCE",
      adapterCode: "LITELLM_COST_MAP",
      authMode: "NONE",
      officialHosts: [],
      region: "global",
      defaultCurrency: "USD",
      scheduleExpression: "P1D",
      autoPublish: false,
      maxAutoChangeRatio: 0.3,
      confirmationRuns: 1,
      config: {},
      status: "DRAFT",
    },
    builtinActions: ["测试获取", "立即同步", "启用", "暂停"],
    builtinActionMap: {
      测试获取: ":id/test",
      立即同步: ":id/sync",
      启用: ":id/enable",
      暂停: ":id/pause",
    },
    emptyTitle: "尚未配置价格源",
    emptyDescription: "可启用内置 LiteLLM/models.dev 参考源，或新增供应商官方 JSON/CSV 价格源。",
  },
  providerPriceSyncRuns: {
    title: "价格同步任务",
    desc: "查看价格获取、标准化、差异和发布结果。",
    apiPath: "/api/provider-price-sync-runs",
    readonly: true,
    fields: [
      "sourceName",
      "sourceClass",
      "adapterCode",
      "triggerType",
      "status",
      "httpStatus",
      "recordsFetched",
      "recordsNormalized",
      "recordsChanged",
      "recordsAutoPublished",
      "recordsReviewRequired",
      "errorCode",
      "errorMessage",
      "startedAt",
      "completedAt",
    ],
    labels: {
      sourceName: "价格源",
      sourceClass: "来源类别",
      adapterCode: "适配器",
      triggerType: "触发方式",
      status: "状态",
      httpStatus: "HTTP 状态",
      recordsFetched: "获取记录",
      recordsNormalized: "标准化记录",
      recordsChanged: "变更记录",
      recordsAutoPublished: "自动发布",
      recordsReviewRequired: "待审核",
      errorCode: "错误码",
      errorMessage: "错误信息",
      startedAt: "开始时间",
      completedAt: "完成时间",
      executionLog: "执行日志",
      snapshots: "原始快照",
      diffs: "价格差异",
    },
    builtinActions: ["查看执行详情"],
    builtinActionMap: { 查看执行详情: "GET :id" },
    relatedFields: ["executionLog", "snapshots", "diffs"],
  },
  providerPriceSnapshots: {
    title: "价格原始快照",
    desc: "保留官方响应、来源地址、哈希、解析器版本和获取时间，支撑审计与回放。",
    apiPath: "/api/provider-price-snapshots",
    readonly: true,
    fields: [
      "sourceName",
      "sourceEndpoint",
      "finalEndpoint",
      "httpStatus",
      "contentType",
      "checksum",
      "responseBytes",
      "parserVersion",
      "fetchedAt",
    ],
    labels: {
      sourceName: "价格源",
      sourceEndpoint: "来源地址",
      finalEndpoint: "最终地址",
      httpStatus: "HTTP 状态",
      contentType: "内容类型",
      checksum: "SHA-256",
      responseBytes: "响应字节数",
      parserVersion: "解析器版本",
      fetchedAt: "获取时间",
      rawContent: "原始内容",
      etag: "ETag",
      lastModified: "最后修改时间",
    },
    builtinActions: ["查看原始内容"],
    builtinActionMap: { 查看原始内容: "GET :id" },
    relatedFields: ["sourceEndpoint", "finalEndpoint", "etag", "lastModified", "checksum", "rawContent"],
  },
  providerPriceDiffs: {
    title: "价格差异审核",
    desc: "低风险变化可自动发布；高风险变化保留旧价格并等待审核。",
    apiPath: "/api/provider-price-diffs",
    readonly: true,
    fields: [
      "sourceName",
      "providerType",
      "providerModelName",
      "region",
      "requestMode",
      "serviceTier",
      "contextTier",
      "diffType",
      "changeRatio",
      "riskLevel",
      "status",
      "decisionReason",
      "decidedBy",
      "decidedAt",
      "createdAt",
    ],
    labels: {
      sourceName: "价格源",
      providerType: "供应商",
      providerModelName: "供应商模型",
      region: "区域",
      requestMode: "调用模式",
      serviceTier: "服务层级",
      contextTier: "上下文阶梯",
      diffType: "差异类型",
      oldValue: "旧价格",
      newValue: "新价格",
      changeRatio: "变化比例",
      riskLevel: "风险等级",
      status: "审核状态",
      decisionReason: "审核意见",
      decidedBy: "审核人",
      decidedAt: "审核时间",
      publishedCatalogId: "发布目录记录",
      createdAt: "发现时间",
    },
    fieldOptions: {
      diffType: opts([
        ["新增模型", "MODEL_ADDED"],
        ["模型疑似移除", "MODEL_REMOVED"],
        ["价格变化", "PRICE_CHANGED"],
        ["币种变化", "CURRENCY_CHANGED"],
        ["计费单位变化", "UNIT_CHANGED"],
        ["计费维度变化", "BILLING_DIMENSION_CHANGED"],
        ["区域变化", "REGION_CHANGED"],
        ["模型映射变化", "MODEL_MAPPING_CHANGED"],
        ["来源结构变化", "SOURCE_STRUCTURE_CHANGED"],
      ]),
      riskLevel: opts([
        ["低", "LOW"],
        ["中", "MEDIUM"],
        ["高", "HIGH"],
        ["严重", "CRITICAL"],
      ]),
      status: opts([
        ["待审核", "PENDING"],
        ["已自动发布", "AUTO_PUBLISHED"],
        ["已批准", "APPROVED"],
        ["已驳回", "REJECTED"],
        ["已忽略", "IGNORED"],
      ]),
    },
    builtinActions: ["查看差异", "批准发布", "驳回"],
    builtinActionMap: {
      查看差异: "GET :id",
      批准发布: ":id/approve",
      驳回: ":id/reject",
    },
    relatedFields: ["oldValue", "newValue", "publishedCatalogId"],
  },
  providerPriceCatalog: {
    title: "供应商官方价格目录",
    desc: "以数据库维护供应商官方公开价格；模型发现后自动匹配并生成生效价格版本。",
    apiPath: "/api/provider-price-catalog",
    fields: [
      "providerType",
      "providerModelName",
      "displayName",
      "currency",
      "billingUnit",
      "inputAmountPer1k",
      "outputAmountPer1k",
      "sourceType",
      "sourceRef",
      "sourceConfidence",
      "effectiveFrom",
      "effectiveTo",
      "revision",
      "status",
      "matchedDeployments",
      "updatedAt",
    ],
    labels: {
      providerType: "供应商类型",
      providerModelName: "供应商模型名",
      displayName: "展示名称",
      aliases: "模型别名",
      currency: "币种",
      billingUnit: "计费单位",
      inputAmountPer1k: "输入金额/千 Token",
      outputAmountPer1k: "输出金额/千 Token",
      sourceType: "来源类型",
      sourceRef: "来源依据",
      sourceConfidence: "来源可信度",
      sourceUpdatedAt: "来源更新时间",
      effectiveFrom: "生效时间",
      effectiveTo: "失效时间",
      revision: "目录版本",
      status: "状态",
      matchedDeployments: "已匹配部署",
      updatedAt: "更新时间",
    },
    requiredFields: [
      "providerType",
      "providerModelName",
      "currency",
      "billingUnit",
      "inputAmountPer1k",
      "outputAmountPer1k",
      "sourceType",
      "sourceRef",
      "effectiveFrom",
      "status",
    ],
    editableFields: [
      "providerType",
      "providerModelName",
      "displayName",
      "aliases",
      "currency",
      "billingUnit",
      "inputAmountPer1k",
      "outputAmountPer1k",
      "sourceType",
      "sourceRef",
      "sourceConfidence",
      "sourceUpdatedAt",
      "effectiveFrom",
      "effectiveTo",
      "status",
    ],
    updateMethod: "patch",
    numberFields: ["inputAmountPer1k", "outputAmountPer1k", "sourceConfidence"],
    optionSources: {
      providerType: {
        path: "/api/provider-templates",
        label: "providerName",
        value: "providerType",
      },
    },
    fieldOptions: {
      currency: opts([["人民币", "CNY"]]),
      billingUnit: opts([["每千 Token", "PER_1K_TOKENS"]]),
      sourceType: opts([
        ["供应商官方公开价", "OFFICIAL_REFERENCE"],
        ["供应商价格接口", "PROVIDER_API"],
        ["人工核验官方价", "MANUAL_VERIFIED"],
      ]),
      status: opts([
        ["启用", "ACTIVE"],
        ["停用", "INACTIVE"],
      ]),
    },
    fieldTypes: {
      providerType: "select",
      aliases: "json",
      currency: "select",
      billingUnit: "select",
      sourceType: "select",
      sourceUpdatedAt: "datetime",
      effectiveFrom: "datetime",
      effectiveTo: "datetime",
      status: "select",
    },
    defaultFormValues: {
      currency: "CNY",
      billingUnit: "PER_1K_TOKENS",
      sourceType: "OFFICIAL_REFERENCE",
      sourceConfidence: 1,
      status: "ACTIVE",
    },
    builtinActions: ["重新匹配"],
    builtinActionMap: { 重新匹配: ":id/rematch" },
    emptyTitle: "尚未维护供应商官方价格",
    emptyDescription: "新增或导入官方价格后，系统会自动匹配已发现模型；后续模型发现也会自动生成生效价格。",
  },
  priceVersions: {
    title: "模型生效价格",
    desc: "展示模型部署自动匹配生成的供应商官方价格版本；日常无需逐条手工录入。",
    apiPath: "/api/price-versions",
    readonly: true,
    fields: [
      "providerType",
      "instanceName",
      "providerModelName",
      "modelDisplayName",
      "currency",
      "inputAmountPer1k",
      "outputAmountPer1k",
      "sourceType",
      "sourceRef",
      "matchType",
      "autoGenerated",
      "version",
      "effectiveFrom",
      "effectiveTo",
      "status",
    ],
    labels: {
      providerType: "供应商类型",
      instanceName: "供应商渠道",
      providerModelName: "供应商模型",
      modelDisplayName: "模型名称",
      currency: "币种",
      inputAmountPer1k: "输入金额/千 Token",
      outputAmountPer1k: "输出金额/千 Token",
      sourceType: "来源类型",
      sourceRef: "来源依据",
      matchType: "匹配方式",
      autoGenerated: "自动生成",
      version: "价格版本",
      effectiveFrom: "生效时间",
      effectiveTo: "失效时间",
      status: "状态",
    },
    numberFields: ["version", "inputAmountPer1k", "outputAmountPer1k"],
    fieldOptions: {
      currency: opts([["人民币", "CNY"]]),
      sourceType: opts([
        ["供应商官方公开价", "OFFICIAL_REFERENCE"],
        ["供应商价格接口", "PROVIDER_API"],
        ["人工核验官方价", "MANUAL_VERIFIED"],
      ]),
      matchType: opts([
        ["精确匹配", "EXACT"],
        ["别名匹配", "ALIAS"],
        ["人工匹配", "MANUAL"],
      ]),
      autoGenerated: yesNo,
      status,
    },
    emptyTitle: "尚未生成模型价格",
    emptyDescription: "请先维护供应商官方价格目录并执行模型发现，系统会自动匹配并生成生效价格版本。",
  },
  budgetRules: {
    title: "预算管理",
    desc: "配置预算范围、预警阈值与超限动作，并读取真实执行状态。",
    apiPath: "/api/budget-rules",
    fields: [
      "scopeType",
      "scopeId",
      "currency",
      "amountLimit",
      "warningThresholdPercent",
      "overLimitAction",
      "degradeModelAlias",
      "effectiveFrom",
      "effectiveTo",
      "status",
    ],
    allowEdit: false,
    labels: {
      scopeType: "预算范围",
      scopeId: "范围对象 ID",
      currency: "币种",
      amountLimit: "预算额度",
      warningThresholdPercent: "预警阈值（%）",
      overLimitAction: "超限动作",
      degradeModelAlias: "降级服务模型",
      effectiveFrom: "生效时间",
      effectiveTo: "失效时间",
      status: "状态",
    },
    requiredFields: [
      "scopeType",
      "scopeId",
      "currency",
      "amountLimit",
      "warningThresholdPercent",
      "overLimitAction",
    ],
    numberFields: ["amountLimit", "warningThresholdPercent"],
    optionSources: {
      scopeId: {
        path: "/api/tenants",
        pathsByValue: {
          TENANT: "/api/tenants",
          PROJECT: "/api/projects",
          APP: "/api/apps",
          API_KEY: "/api/keys",
        },
        dependsOn: "scopeType",
        label: "name",
        value: "id",
      },
      degradeModelAlias: {
        path: "/api/platform-models",
        label: "displayName",
        value: "platformModelName",
      },
    },
    fieldOptions: {
      scopeType: opts([
        ["租户", "TENANT"],
        ["项目", "PROJECT"],
        ["应用", "APP"],
        ["API Key", "API_KEY"],
      ]),
      currency: opts([["人民币", "CNY"]]),
      overLimitAction: opts([
        ["拒绝请求", "BLOCK"],
        ["仅告警", "ALERT_ONLY"],
        ["降级模型", "DEGRADE"],
      ]),
      status,
    },
    fieldTypes: {
      scopeType: "select",
      scopeId: "select",
      currency: "select",
      overLimitAction: "select",
      degradeModelAlias: "select",
      effectiveFrom: "datetime",
      effectiveTo: "datetime",
    },
    builtinActions: ["提交审批", "审批后生效", "退役", "查看版本"],
    builtinActionMap: {
      提交审批: ":id/submit",
      审批后生效: ":id/activate",
      退役: ":id/retire",
      查看版本: "GET :id/versions",
    },
    actionForms: {
      提交审批: {
        fields: ["decisionReason"],
        labels: { decisionReason: "提交理由" },
        requiredFields: ["decisionReason"],
      },
    },
    relatedFields: ["version", "sourceAction", "createdBy", "createdAt"],
  },
  costStatements: {
    title: "内部成本单",
    desc: "按组织、项目、应用、Key、模型和渠道汇总本月真实成本。",
    apiPath: `/api/cost-statements?from=${encodeURIComponent(statementFrom)}&to=${encodeURIComponent(statementTo)}`,
    readonly: true,
    fields: [
      "tenantId",
      "projectId",
      "appId",
      "apiKeyId",
      "modelAlias",
      "providerId",
      "requestCount",
      "totalTokens",
      "actualCost",
      "currency",
    ],
    labels: {
      tenantId: "租户",
      projectId: "项目",
      appId: "应用",
      apiKeyId: "API Key",
      modelAlias: "模型",
      providerId: "供应商渠道",
      requestCount: "请求数",
      totalTokens: "Token",
      actualCost: "实际成本",
      currency: "币种",
    },
  },
  providerHealth: {
    title: "渠道健康",
    desc: "读取渠道连接测试、最近成功时间和模型可用性。",
    apiPath: "/api/provider-instances",
    readonly: true,
    fields: [
      "instanceName",
      "region",
      "lastConnectionTestStatus",
      "lastConnectionTestAt",
      "healthStatus",
      "enabledModels",
      "status",
    ],
    labels: {
      instanceName: "供应商渠道",
      region: "区域",
      lastConnectionTestStatus: "连接测试",
      lastConnectionTestAt: "测试时间",
      healthStatus: "健康状态",
      enabledModels: "启用模型",
      status: "状态",
    },
    builtinActions: ["连接测试"],
    builtinActionMap: { 连接测试: ":id/test-connection" },
  },
  alerts: {
    title: "告警",
    desc: "处理模型消失、能力失败、预算和成本异常等真实事件。",
    apiPath: "/api/alerts",
    readonly: true,
    fields: [
      "alertType",
      "severity",
      "resourceType",
      "resourceId",
      "title",
      "detail",
      "status",
      "acknowledgedBy",
      "acknowledgedAt",
      "resolvedBy",
      "resolvedAt",
      "createdAt",
    ],
    labels: {
      alertType: "告警类型",
      severity: "级别",
      resourceType: "对象类型",
      resourceId: "对象 ID",
      title: "告警标题",
      detail: "详情",
      status: "状态",
      acknowledgedBy: "确认人",
      acknowledgedAt: "确认时间",
      resolvedBy: "解决人",
      resolvedAt: "解决时间",
      createdAt: "发生时间",
    },
    fieldOptions: {
      severity: opts([
        ["严重", "CRITICAL"],
        ["高", "HIGH"],
        ["警告", "WARNING"],
        ["信息", "INFO"],
      ]),
      status,
    },
    builtinActions: ["确认", "解决"],
    builtinActionMap: {
      确认: "PATCH :id/acknowledge",
      解决: "PATCH :id/resolve",
    },
  },
  audit: {
    title: "操作审计",
    desc: "查询价格、路由、模型、Key、预算和敏感查看的完整审计轨迹。",
    apiPath: "/api/audit",
    readonly: true,
    fields: [
      "actorId",
      "actorName",
      "action",
      "objectType",
      "objectId",
      "beforeValue",
      "afterValue",
      "ipAddress",
      "userAgent",
      "createdAt",
    ],
    labels: {
      actorId: "操作人 ID",
      actorName: "操作人",
      action: "操作",
      objectType: "对象类型",
      objectId: "对象 ID",
      beforeValue: "变更前",
      afterValue: "变更后",
      ipAddress: "来源 IP",
      userAgent: "客户端",
      createdAt: "时间",
    },
  },
  sensitiveAccess: {
    title: "敏感查看记录",
    desc: "记录敏感数据查看的理由、审批与访问结果。",
    apiPath: "/api/audit/sensitive-access",
    readonly: true,
    fields: [
      "actorId",
      "objectType",
      "objectId",
      "reason",
      "fieldsViewed",
      "createdAt",
    ],
    labels: {
      actorId: "查看人",
      objectType: "资源类型",
      objectId: "资源 ID",
      reason: "查看理由",
      fieldsViewed: "查看字段",
      createdAt: "时间",
    },
  },
  reconciliations: {
    title: "供应商对账",
    desc: "录入真实供应商账单并展示与系统成本的差异。",
    apiPath: "/api/provider-reconciliations",
    fields: [
      "providerInstanceId",
      "periodStart",
      "periodEnd",
      "currency",
      "internalCost",
      "providerAmount",
      "differenceAmount",
      "tokenDifference",
      "priceDifference",
      "exchangeRateDifference",
      "taxDifference",
      "status",
      "sourceRef",
      "notes",
      "confirmedBy",
      "confirmedAt",
      "resolvedBy",
      "resolvedAt",
      "createdAt",
    ],
    labels: {
      providerInstanceId: "供应商渠道",
      periodStart: "开始日期",
      periodEnd: "结束日期",
      currency: "币种",
      internalCost: "系统成本",
      providerAmount: "供应商账单金额",
      providerTokens: "供应商 Token",
      providerExchangeRateAdjustment: "供应商汇率调整",
      providerTaxAmount: "供应商税费",
      differenceAmount: "总差异",
      tokenDifference: "Token 差异",
      priceDifference: "价格差异",
      exchangeRateDifference: "汇率差异",
      taxDifference: "税费差异",
      status: "状态",
      sourceRef: "账单依据",
      notes: "说明",
      confirmedBy: "确认人",
      confirmedAt: "确认时间",
      resolvedBy: "解决人",
      resolvedAt: "解决时间",
      createdAt: "创建时间",
    },
    requiredFields: [
      "providerInstanceId",
      "periodStart",
      "periodEnd",
      "currency",
      "providerAmount",
      "providerTokens",
      "providerExchangeRateAdjustment",
      "providerTaxAmount",
      "sourceRef",
    ],
    numberFields: [
      "providerAmount",
      "providerTokens",
      "providerExchangeRateAdjustment",
      "providerTaxAmount",
    ],
    allowEdit: false,
    editableFields: [
      "providerInstanceId",
      "periodStart",
      "periodEnd",
      "currency",
      "providerAmount",
      "providerTokens",
      "providerExchangeRateAdjustment",
      "providerTaxAmount",
      "sourceRef",
      "notes",
    ],
    optionSources: { providerInstanceId: channelSource },
    fieldOptions: { currency: opts([["人民币", "CNY"]]), status },
    fieldTypes: {
      providerInstanceId: "select",
      periodStart: "date",
      periodEnd: "date",
      currency: "select",
      notes: "textarea",
    },
    builtinActions: ["确认差异", "确认解决", "导出"],
    builtinActionMap: {
      确认差异: ":id/confirm",
      确认解决: ":id/resolve",
      导出: "DOWNLOAD :id/export",
    },
    actionForms: {
      确认解决: {
        fields: ["reason"],
        labels: { reason: "解决原因" },
        requiredFields: ["reason"],
      },
    },
  },
  approvals: {
    title: "治理审批",
    desc: "集中处理模型、价格、路由、预算等高风险变化。",
    apiPath: "/api/governance/approvals",
    readonly: true,
    fields: [
      "resourceType",
      "resourceId",
      "riskLevel",
      "reason",
      "requestedBy",
      "requestedAt",
      "decisionReason",
      "status",
    ],
    labels: {
      resourceType: "对象类型",
      resourceId: "对象 ID",
      riskLevel: "风险等级",
      reason: "变更理由",
      requestedBy: "提交人",
      requestedAt: "提交时间",
      decisionReason: "审批意见",
      status: "状态",
    },
    builtinActions: ["批准", "拒绝"],
    builtinActionMap: { 批准: ":id/approve", 拒绝: ":id/reject" },
    actionForms: {
      批准: {
        fields: ["decisionReason"],
        labels: { decisionReason: "审批意见" },
      },
      拒绝: {
        fields: ["decisionReason"],
        labels: { decisionReason: "拒绝理由" },
        requiredFields: ["decisionReason"],
      },
    },
  },
  versions: {
    title: "发布与回滚",
    desc: "查询已发布版本并回滚到可验证的稳定版本。",
    apiPath: "/api/governance/versions",
    readonly: true,
    fields: [
      "resourceType",
      "resourceId",
      "version",
      "sourceAction",
      "createdBy",
      "createdAt",
    ],
    labels: {
      resourceType: "对象类型",
      resourceId: "对象 ID",
      version: "版本",
      sourceAction: "来源动作",
      createdBy: "创建人",
      createdAt: "创建时间",
    },
    builtinActions: ["回滚"],
    builtinActionMap: { 回滚: "PATCH :id/rollback" },
  },
  errorCodes: {
    title: "错误码",
    desc: "从控制面读取当前部署支持的稳定错误码及处置建议。",
    apiPath: "/api/error-codes",
    readonly: true,
    fields: ["code", "httpStatus", "category", "message", "suggestion"],
    labels: {
      code: "错误码",
      httpStatus: "HTTP 状态",
      category: "类别",
      message: "说明",
      suggestion: "处置建议",
    },
    emptyTitle: "当前未返回错误码目录",
    emptyDescription: "请确认控制面错误码目录端点已启用。",
  },
  settings: {
    title: "系统基础设置",
    desc: "读取并维护当前部署允许变更的非敏感系统参数。",
    apiPath: "/api/system-settings",
    fields: ["group", "key", "value", "description", "sensitive", "updatedAt"],
    labels: {
      group: "设置分组",
      key: "设置键",
      value: "当前值",
      description: "设置说明",
      sensitive: "敏感设置",
      updatedAt: "更新时间",
    },
    allowCreate: false,
    editableFields: ["key", "value", "description", "sensitive"],
    updateKey: "key",
    requiredFields: ["key"],
    fieldOptions: { sensitive: yesNo },
    fieldTypes: { sensitive: "select" },
  },
};

export const resourceRoutes = [
  ["provider-templates", "providerTemplates"],
  ["provider-channels", "providerChannels"],
  ["model-references", "modelReferences"],
  ["model-deployments", "modelDeployments"],
  ["service-models", "serviceModels"],
  ["capability-validations", "capabilityValidations"],
  ["data-sources", "dataSources"],
  ["sync-jobs", "syncJobs"],
  ["model-discoveries", "modelDiscoveries"],
  ["discovery-diffs", "discoveryDiffs"],
  ["public-price-references", "publicPriceReferences"],
  ["provider-price-sources", "providerPriceSources"],
  ["provider-price-sync-runs", "providerPriceSyncRuns"],
  ["provider-price-snapshots", "providerPriceSnapshots"],
  ["provider-price-diffs", "providerPriceDiffs"],
  ["provider-price-catalog", "providerPriceCatalog"],
  ["price-versions", "priceVersions"],
  ["budget-rules", "budgetRules"],
  ["provider-health", "providerHealth"],
  ["alerts", "alerts"],
  ["audit", "audit"],
  ["sensitive-access", "sensitiveAccess"],
  ["provider-reconciliations", "reconciliations"],
  ["approvals", "approvals"],
  ["versions", "versions"],
  ["error-codes", "errorCodes"],
  ["system-settings", "settings"],
] as const;
