type Option = { label: string; value: unknown };
type Source = {
  path: string;
  label: string;
  value: string;
  multiple?: boolean;
  dependsOn?: string;
  filterBy?: string;
  query?: Record<string, string | number | boolean | undefined>;
  pathsByValue?: Record<string, string>;
  serialize?: "json" | "array";
  autofill?: Record<string, string>;
};
type ActionPrecondition = {
  path: string;
  idField: string;
  field: string;
  equals: unknown;
  message: string;
};
export type ResourceProps = {
  title: string;
  desc: string;
  descNoWrap?: boolean;
  apiPath: string;
  queryParams?: Record<string, string | number | boolean | undefined>;
  fields: string[];
  labels: Record<string, string>;
  requiredFields?: string[];
  numberFields?: string[];
  readonly?: boolean;
  allowCreate?: boolean;
  createLabel?: string;
  allowEdit?: boolean;
  editableFields?: string[];
  readonlyFields?: string[];
  immutableFields?: string[];
  detailFields?: string[];
  compactForm?: boolean;
  internalScroll?: boolean;
  updateKey?: string;
  updateMethod?: "put" | "patch";
  fieldOptions?: Record<string, Option[]>;
  fieldPresets?: Record<string, Record<string, Record<string, unknown>>>;
  optionSources?: Record<string, Source>;
  fieldTypes?: Record<string, string>;
  statePath?: string;
  stateLabel?: string;
  stateMethod?: "post" | "patch";
  builtinActions?: string[];
  builtinActionMap?: Record<string, string>;
  refreshOnErrorActions?: string[];
  actionPreconditions?: Record<string, ActionPrecondition>;
  relatedFields?: string[];
  actionForms?: Record<
    string,
    {
      fields: string[];
      labels: Record<string, string>;
      requiredFields?: string[];
      fieldOptions?: Record<string, Option[]>;
      fieldTypes?: Record<string, string>;
      rowFields?: Record<string, string>;
    }
  >;
  relatedLabels?: Record<string, string>;
  exportPath?: string;
  emptyTitle?: string;
  emptyDescription?: string;
  defaultSort?: string;
  defaultOrder?: "asc" | "desc";
  sortFallbackFields?: string[];
  columnWidths?: Record<string, string>;
  actionColumnWidth?: string;
  noHorizontalScroll?: boolean;
  showBottomTotal?: boolean;
  hideTopTotal?: boolean;
  showCellTooltip?: boolean;
  detailSections?: Array<{
    title: string;
    path: string;
    fields: string[];
    labels: Record<string, string>;
  }>;
  defaultFormValues?: Record<string, unknown>;
};

const opts = (values: [string, unknown][]) =>
  values.map(([label, value]) => ({ label, value }));
const status = opts([
  ["草稿", "DRAFT"],
  ["待审核", "PENDING_REVIEW"],
  ["已批准", "APPROVED"],
  ["启用", "ACTIVE"],
  ["暂停", "SUSPENDED"],
  ["已完成", "COMPLETED"],
  ["失败", "FAILED"],
  ["退役", "RETIRED"],
]);
const yesNo = opts([
  ["是", true],
  ["否", false],
]);
const channelSource = {
  path: "/api/provider-instances",
  label: "instanceName",
  value: "id",
};
const tenantSource = { path: "/api/tenants", label: "name", value: "id" };
const providerChannelDetailFields = [
  "instanceName",
  "providerTemplateId",
  "apiStyle",
  "apiBase",
  "region",
  "environment",
  "owner",
  "rateLimitRpm",
  "rateLimitTpm",
  "keyStatus",
  "healthStatus",
  "lastConnectionTestStatus",
  "lastConnectionTestAt",
  "lastConnectionTestError",
  "lastConnectionTestHost",
  "lastConnectionTestPort",
  "status",
];
const providerChannelDetailSections = [
  {
    title: "连接测试详情",
    path: "/api/provider-instances/:id",
    fields: [
      "lastConnectionTestStatus",
      "lastConnectionTestAt",
      "lastConnectionTestError",
      "lastConnectionTestHost",
      "lastConnectionTestPort",
    ],
    labels: {
      lastConnectionTestStatus: "最近连接测试状态",
      lastConnectionTestAt: "最近连接测试时间",
      lastConnectionTestError: "异常原因",
      lastConnectionTestHost: "测试目标主机",
      lastConnectionTestPort: "测试目标端口",
    },
  },
];
const statementNow = new Date(),
  statementFrom = new Date(
    Date.UTC(statementNow.getUTCFullYear(), statementNow.getUTCMonth(), 1),
  ).toISOString(),
  statementTo = new Date(
    Date.UTC(statementNow.getUTCFullYear(), statementNow.getUTCMonth() + 1, 1),
  ).toISOString();

export const resources: Record<string, ResourceProps> = {
  providerTemplates: {
    title: "供应商模板",
    desc: "独立维护供应商协议、鉴权方式与模型目录模板。",
    apiPath: "/api/provider-templates",
    fields: [
      "providerName",
      "providerType",
      "protocol",
      "defaultApiBase",
      "authType",
      "status",
    ],
    labels: {
      providerName: "供应商名称",
      providerType: "供应商类型",
      protocol: "协议",
      defaultApiBase: "默认 API 地址",
      authType: "鉴权方式",
      status: "状态",
    },
    requiredFields: [
      "providerName",
      "providerType",
      "protocol",
      "defaultApiBase",
      "authType",
    ],
    updateMethod: "patch",
    fieldOptions: {
      protocol: opts([
        ["开放接口兼容", "openai_compatible"],
        ["微软云协议", "azure"],
        ["安索匹克协议", "anthropic"],
        ["谷歌双子座协议", "gemini"],
        ["本地推理协议", "vllm"],
      ]),
      authType: opts([
        ["Bearer 密钥", "BEARER"],
        ["API Key 请求头", "API_KEY_HEADER"],
        ["无需鉴权", "NONE"],
      ]),
      status,
    },
    fieldTypes: { protocol: "select", authType: "select", status: "select" },
    builtinActions: ["启用为渠道", "复制", "查看模型"],
    builtinActionMap: {
      启用为渠道: ":id/enable",
      复制: ":id/copy",
      查看模型: "GET :id/model-templates",
    },
    actionForms: {
      启用为渠道: {
        fields: ["instanceName", "apiBase", "region", "environment", "owner"],
        labels: {
          instanceName: "渠道名称",
          apiBase: "API 地址",
          region: "区域",
          environment: "环境",
          owner: "负责人",
        },
        requiredFields: ["instanceName", "apiBase"],
        fieldOptions: {
          region: opts([
            ["中国", "CN"],
            ["日本", "JP"],
            ["美国", "US"],
            ["欧洲", "EU"],
          ]),
          environment: opts([
            ["开发", "开发"],
            ["测试", "测试"],
            ["生产", "生产"],
          ]),
        },
      },
    },
    relatedFields: [
      "providerModelName",
      "defaultDisplayName",
      "supportedEndpoints",
      "status",
    ],
  },
  providerChannels: {
    title: "供应商渠道",
    desc: "承载真实连接、密钥、区域、限流与模型发现。",
    apiPath: "/api/provider-instances",
    defaultSort: "createdAt",
    defaultOrder: "desc",
    fields: [
      "instanceName",
      "providerTemplateId",
      "apiBase",
      "environment",
      "rateLimitRpm",
      "rateLimitTpm",
      "keyStatus",
      "healthStatus",
      "status",
    ],
    detailFields: providerChannelDetailFields,
    readonlyFields: ["apiStyle"],
    immutableFields: ["providerTemplateId"],
    editableFields: [
      "instanceName",
      "providerTemplateId",
      "apiStyle",
      "apiBase",
      "region",
      "environment",
      "owner",
      "rateLimitRpm",
      "rateLimitTpm",
      "status",
    ],
    columnWidths: {
      instanceName: "110px",
      providerTemplateId: "105px",
      apiBase: "170px",
      environment: "58px",
      rateLimitRpm: "66px",
      rateLimitTpm: "82px",
      keyStatus: "70px",
      healthStatus: "70px",
      status: "60px",
    },
    labels: {
      instanceName: "渠道名称",
      providerTemplateId: "供应商模板",
      apiStyle: "协议",
      apiBase: "API 地址",
      region: "区域",
      environment: "环境",
      owner: "负责人",
      rateLimitRpm: "每分钟请求",
      rateLimitTpm: "每分钟 Token",
      keyStatus: "密钥状态",
      healthStatus: "健康状态",
      lastConnectionTestStatus: "最近连接测试状态",
      lastConnectionTestAt: "最近连接测试时间",
      lastConnectionTestError: "异常原因",
      lastConnectionTestHost: "测试目标主机",
      lastConnectionTestPort: "测试目标端口",
      status: "状态",
    },
    requiredFields: [
      "instanceName",
      "providerTemplateId",
      "apiStyle",
      "apiBase",
    ],
    numberFields: ["rateLimitRpm", "rateLimitTpm"],
    optionSources: {
      providerTemplateId: {
        path: "/api/provider-templates",
        label: "providerName",
        value: "id",
        autofill: { apiStyle: "protocol", apiBase: "defaultApiBase" },
      },
    },
    fieldOptions: {
      apiStyle: opts([
        ["开放接口兼容", "openai_compatible"],
        ["微软云协议", "azure"],
        ["安索匹克协议", "anthropic"],
        ["谷歌双子座协议", "gemini"],
        ["本地推理协议", "vllm"],
      ]),
      region: opts([
        ["中国", "CN"],
        ["日本", "JP"],
        ["美国", "US"],
        ["欧洲", "EU"],
      ]),
      environment: opts([
        ["开发", "开发"],
        ["测试", "测试"],
        ["生产", "生产"],
      ]),
      lastConnectionTestStatus: opts([
        ["成功", "成功"],
        ["失败", "失败"],
      ]),
      status: opts([
        ["启用", "启用"],
        ["暂停", "暂停"],
        ["停用", "停用"],
      ]),
    },
    fieldTypes: {
      apiStyle: "select",
      region: "select",
      environment: "select",
      status: "select",
    },
    detailSections: providerChannelDetailSections,
    statePath: "status",
    builtinActions: ["托管密钥", "连接测试", "发现模型"],
    refreshOnErrorActions: ["连接测试"],
    builtinActionMap: {
      托管密钥: "POST /api/provider-secrets",
      连接测试: ":id/test-connection",
      发现模型: ":id/discover-models",
    },
    actionForms: {
      托管密钥: {
        fields: ["secretName", "secretValue"],
        labels: { secretName: "密钥名称", secretValue: "密钥值" },
        requiredFields: ["secretValue"],
        fieldTypes: { secretValue: "password" },
        rowFields: { providerInstanceId: "id" },
      },
    },
  },
  modelReferences: {
    title: "公共模型参考库",
    desc: "展示有来源、可信度和快照依据的公共模型元数据。",
    apiPath: "/api/model-references",
    fields: [
      "canonicalName",
      "displayName",
      "vendor",
      "family",
      "capabilityClaims",
      "contextLength",
      "sourceType",
      "sourceRef",
      "sourceConfidence",
      "status",
      "version",
      "updatedAt",
    ],
    labels: {
      canonicalName: "模型标识",
      displayName: "展示名称",
      vendor: "供应商",
      family: "模型家族",
      capabilityClaims: "能力声明",
      contextLength: "上下文窗口",
      sourceType: "来源类型",
      sourceRef: "来源依据",
      sourceConfidence: "可信度",
      status: "状态",
      version: "版本",
      updatedAt: "更新时间",
    },
    requiredFields: ["canonicalName", "displayName", "sourceType"],
    numberFields: ["contextLength", "sourceConfidence"],
    allowEdit: false,
    optionSources: {
      capabilityClaims: {
        path: "/api/model-capability-tags",
        label: "displayName",
        value: "code",
        multiple: true,
        serialize: "array",
      },
    },
    fieldOptions: {
      sourceType: opts([
        ["供应商接口", "PROVIDER_API"],
        ["公共参考来源", "PUBLIC_REFERENCE"],
        ["文件导入", "FILE_IMPORT"],
      ]),
      status,
    },
    fieldTypes: { capabilityClaims: "multiselect", sourceType: "select" },
    emptyTitle: "尚无公共模型参考数据",
    emptyDescription: "同步任务产生并审核的数据会显示在这里。",
  },
  modelDeployments: {
    title: "模型部署",
    desc: "展示渠道发现的真实模型部署。真实探测只确认技术可用性，进入生产路由前还必须匹配正式成本价格并由平台管理员确认。",
    apiPath: "/api/model-deployment-governance",
    readonly: true,
    defaultSort: "createdAt",
    defaultOrder: "desc",
    fields: [
      "instanceName",
      "providerType",
      "providerModelName",
      "displayName",
      "discoveryStatus",
      "missingStreak",
      "healthStatus",
      "priceStatus",
      "productionStatus",
      "latestProbeStatus",
      "latestProbeAt",
      "lastSeenAt",
    ],
    detailFields: [
      "providerInstanceId",
      "instanceName",
      "providerType",
      "providerRegion",
      "providerModelName",
      "displayName",
      "discoveryStatus",
      "missingStreak",
      "healthStatus",
      "priceStatus",
      "productionStatus",
      "productionReviewedBy",
      "productionReviewedAt",
      "productionReviewReason",
      "firstSeenAt",
      "lastSeenAt",
      "missingAt",
      "version",
    ],
    labels: {
      providerInstanceId: "供应商渠道 ID",
      instanceName: "渠道名称",
      providerType: "供应商类型",
      providerRegion: "渠道区域",
      providerModelName: "渠道模型名",
      displayName: "展示名称",
      discoveryStatus: "发现状态",
      missingStreak: "连续缺失次数",
      healthStatus: "技术健康",
      priceStatus: "成本价格",
      productionStatus: "生产准入",
      latestProbeStatus: "最近探测",
      latestProbeAt: "最近探测时间",
      productionReviewedBy: "生产审核人",
      productionReviewedAt: "生产审核时间",
      productionReviewReason: "审核说明",
      firstSeenAt: "首次发现",
      lastSeenAt: "最后发现",
      missingAt: "确认消失时间",
      version: "版本",
    },
    optionSources: { providerInstanceId: channelSource },
    fieldOptions: {
      discoveryStatus: opts([
        ["已发现", "DISCOVERED"],
        ["疑似缺失", "MISSING_SUSPECTED"],
        ["确认消失", "MISSING_CONFIRMED"],
        ["已恢复", "RECOVERED"],
      ]),
      healthStatus: opts([
        ["待探测", "UNKNOWN"],
        ["待探测", "PROBE_PENDING"],
        ["健康", "HEALTHY"],
        ["异常", "UNHEALTHY"],
        ["不可用", "UNAVAILABLE"],
      ]),
      priceStatus: opts([
        ["已匹配官方价", "MATCHED_OFFICIAL"],
        ["已匹配渠道价", "MATCHED_CHANNEL"],
        ["已匹配合同价", "MATCHED_CONTRACT"],
        ["缺少正式价格", "MISSING"],
        ["价格冲突", "CONFLICT"],
      ]),
      productionStatus: opts([
        ["候选", "CANDIDATE"],
        ["待审核", "READY_FOR_REVIEW"],
        ["待审核", "PENDING_REVIEW"],
        ["已批准", "APPROVED"],
        ["已拒绝", "REJECTED"],
        ["已暂停", "SUSPENDED"],
      ]),
      latestProbeStatus: opts([
        ["待探测", "PROBE_PENDING"],
        ["通过", "PASSED"],
        ["失败", "FAILED"],
      ]),
    },
    fieldTypes: { providerInstanceId: "select" },
    builtinActions: ["真实探测", "变更生产状态", "有效成本价格"],
    builtinActionMap: {
      真实探测: "POST /api/channel-model-deployments/:id/probe",
      变更生产状态: "POST :id/production-transition",
      有效成本价格: "GET :id/effective-cost-price",
    },
    actionForms: {
      真实探测: {
        fields: ["capabilityCode"],
        labels: { capabilityCode: "探测能力" },
        requiredFields: ["capabilityCode"],
        fieldOptions: {
          capabilityCode: opts([
            ["对话", "CHAT"],
            ["流式对话", "STREAM"],
            ["向量嵌入", "EMBEDDING"],
          ]),
        },
      },
      变更生产状态: {
        fields: ["decision", "reason"],
        labels: { decision: "生产状态", reason: "操作说明" },
        requiredFields: ["decision"],
        fieldOptions: {
          decision: opts([
            ["确认进入生产", "APPROVE"],
            ["拒绝进入生产", "REJECT"],
            ["暂停生产", "SUSPEND"],
          ]),
        },
        fieldTypes: { decision: "select" },
      },
    },
    relatedFields: [
      "priceVersionId",
      "priceLayer",
      "currency",
      "billingBasis",
      "billingQuantity",
      "inputUnitPrice",
      "cacheReadUnitPrice",
      "cacheWriteUnitPrice",
      "outputUnitPrice",
      "resolutionReason",
    ],
    relatedLabels: {
      priceVersionId: "价格版本",
      priceLayer: "成本价格层",
      currency: "币种",
      billingBasis: "计费对象",
      billingQuantity: "计费基数",
      inputUnitPrice: "输入价格",
      cacheReadUnitPrice: "缓存命中价格",
      cacheWriteUnitPrice: "缓存写入价格",
      outputUnitPrice: "输出价格",
      resolutionReason: "选择原因",
    },
    detailSections: [
      {
        title: "最近能力验证",
        path: "/api/channel-model-deployments/:id/capability-validations",
        fields: ["capabilityCode", "testType", "status", "httpStatus", "latencyMs", "validatedAt"],
        labels: { capabilityCode: "能力", testType: "验证类型", status: "结果", httpStatus: "HTTP 状态", latencyMs: "耗时（毫秒）", validatedAt: "验证时间" },
      },
    ],
  },
  modelDiscoveryCandidates: {
    title: "模型候选",
    desc: "汇总官方价格页与供应商渠道发现的新模型。仅价格页发现的记录不可直接调用；渠道发现后仍需完成健康探测、价格匹配和生产准入。",
    apiPath: "/api/model-discovery-candidates",
    readonly: true,
    noHorizontalScroll: false,
    columnWidths: {
      providerType: "84px",
      candidateModelName: "140px",
      displayName: "140px",
      region: "60px",
      firstSourceType: "90px",
      priceSourceCount: "70px",
      channelVerifiedCount: "80px",
      currentChannelCount: "85px",
      lastVerificationAt: "120px",
      lastVerificationResult: "75px",
      activePriceCount: "70px",
      availabilityStatus: "105px",
      lastSeenAt: "96px",
    },
    fields: [
      "providerType",
      "candidateModelName",
      "displayName",
      "region",
      "firstSourceType",
      "priceSourceCount",
      "channelVerifiedCount",
      "currentChannelCount",
      "lastVerificationAt",
      "lastVerificationResult",
      "activePriceCount",
      "availabilityStatus",
      "lastSeenAt",
    ],
    detailFields: [
      "providerType",
      "candidateModelName",
      "displayName",
      "region",
      "firstSourceType",
      "firstSourceRef",
      "firstSeenAt",
      "lastSeenAt",
      "priceSourceCount",
      "channelVerifiedCount",
      "currentChannelCount",
      "usableDeploymentCount",
      "lastVerificationAt",
      "lastVerificationResult",
      "lastVerificationMessage",
      "verificationAttemptCount",
      "activePriceCount",
      "availabilityStatus",
      "verifiedAt",
      "status",
      "metadata",
    ],
    labels: {
      providerType: "供应商类型",
      candidateModelName: "候选模型名",
      displayName: "展示名称",
      region: "区域",
      firstSourceType: "首次发现来源",
      firstSourceRef: "首次发现依据",
      firstSeenAt: "首次发现时间",
      lastSeenAt: "最近发现时间",
      priceSourceCount: "价格源发现次数",
      channelVerifiedCount: "已匹配渠道数",
      currentChannelCount: "当前渠道部署数",
      usableDeploymentCount: "生产可用部署数",
      lastVerificationAt: "最近验证时间",
      lastVerificationResult: "验证结果",
      lastVerificationMessage: "验证说明",
      verificationAttemptCount: "验证次数",
      activePriceCount: "有效官方价格数",
      availabilityStatus: "当前可用性",
      verifiedAt: "渠道验证时间",
      status: "候选状态",
      metadata: "候选元数据",
    },
    fieldOptions: {
      firstSourceType: opts([
        ["官方价格页", "PRICE_SOURCE"],
        ["供应商渠道", "CHANNEL_DISCOVERY"],
      ]),
      availabilityStatus: opts([
        ["可调用", "AVAILABLE"],
        ["渠道已发现，待准入", "CHANNEL_DISCOVERED"],
        ["仅价格发现，不可调用", "PRICE_ONLY"],
      ]),
      status: opts([
        ["仅价格发现（不可调用）", "PRICE_ONLY"],
        ["渠道已发现（待生产准入）", "CHANNEL_VERIFIED"],
        ["已忽略", "IGNORED"],
      ]),
    },
    builtinActions: ["核验渠道"],
    builtinActionMap: { 核验渠道: ":id/verify" },
    emptyTitle: "尚无新模型候选",
    emptyDescription: "官方价格同步或渠道模型发现后，新模型会自动进入候选池。",
  },
  providerModelAliases: {
    title: "模型别名审核",
    desc: "维护供应商模型别名、稳定别名、版本关系和变体关系。只有审核通过且未形成循环的关系才参与价格匹配。",
    apiPath: "/api/provider-model-aliases",
    createLabel: "新增受控别名",
    allowEdit: false,
    fields: [
      "providerType",
      "providerModelName",
      "targetProviderModelName",
      "relationType",
      "region",
      "sourceType",
      "reviewStatus",
      "reviewedBy",
      "reviewedAt",
      "effectiveFrom",
      "effectiveTo",
    ],
    detailFields: [
      "providerType",
      "providerModelName",
      "targetProviderModelName",
      "relationType",
      "region",
      "sourceType",
      "sourceRef",
      "evidenceHash",
      "reviewStatus",
      "reviewReason",
      "reviewedBy",
      "reviewedAt",
      "effectiveFrom",
      "effectiveTo",
      "createdAt",
      "updatedAt",
    ],
    editableFields: [
      "providerType",
      "providerModelName",
      "targetProviderModelName",
      "relationType",
      "region",
      "sourceRef",
      "reason",
      "effectiveFrom",
      "effectiveTo",
    ],
    labels: {
      providerType: "供应商类型",
      providerModelName: "别名模型",
      targetProviderModelName: "目标模型",
      relationType: "关系类型",
      region: "区域",
      sourceType: "证据来源类型",
      sourceRef: "证据地址",
      evidenceHash: "证据哈希",
      reason: "建立理由",
      reviewStatus: "审核状态",
      reviewReason: "审核意见",
      reviewedBy: "审核人",
      reviewedAt: "审核时间",
      effectiveFrom: "生效时间",
      effectiveTo: "失效时间",
      createdAt: "创建时间",
      updatedAt: "更新时间",
    },
    requiredFields: [
      "providerType",
      "providerModelName",
      "targetProviderModelName",
      "relationType",
      "region",
      "reason",
    ],
    optionSources: {
      providerType: {
        path: "/api/provider-templates",
        label: "providerName",
        value: "providerType",
      },
    },
    fieldOptions: {
      relationType: opts([
        ["精确别名", "EXACT_ALIAS"],
        ["稳定别名", "STABLE_ALIAS"],
        ["具体版本", "VERSION_OF"],
        ["模型变体", "VARIANT_OF"],
      ]),
      region: opts([
        ["全球", "global"],
        ["中国", "cn"],
        ["美国", "us"],
        ["欧洲", "eu"],
        ["亚太", "apac"],
      ]),
      sourceType: opts([
        ["官方页面", "OFFICIAL_REFERENCE"],
        ["人工核验", "MANUAL_VERIFIED"],
      ]),
      reviewStatus: opts([
        ["待审核", "PENDING_REVIEW"],
        ["已批准", "APPROVED"],
        ["迁移兼容批准", "MIGRATED_APPROVED"],
        ["已拒绝", "REJECTED"],
      ]),
    },
    fieldTypes: {
      providerType: "select",
      relationType: "select",
      region: "select",
      sourceType: "select",
      reviewStatus: "select",
      effectiveFrom: "datetime",
      effectiveTo: "datetime",
    },
    defaultFormValues: {
      relationType: "STABLE_ALIAS",
      region: "global",
    },
    builtinActions: ["批准", "拒绝"],
    builtinActionMap: { 批准: ":id/approve", 拒绝: ":id/reject" },
    actionForms: {
      拒绝: {
        fields: ["reason"],
        labels: { reason: "拒绝原因" },
        requiredFields: ["reason"],
      },
    },
    emptyTitle: "尚无模型别名关系",
    emptyDescription: "官方价格解析产生的别名候选或管理员新增的受控关系会显示在这里。",
  },
  serviceModels: {
    title: "企业服务模型",
    desc: "发布前可执行“发布检查”，逐项确认路由、候选部署、探测、价格和渠道状态；存在异常时先按提示处理，再发布。",
    apiPath: "/api/platform-models",
    createLabel: "新建草稿",
    defaultSort: "createdAt",
    defaultOrder: "desc",
    fields: [
      "platformModelName",
      "displayName",
      "providerInstanceIds",
      "actualModels",
      "routePolicyId",
      "routeStatus",
      "visibilityScope",
      "approvalRequired",
      "status",
    ],
    labels: {
      platformModelName: "服务模型名",
      displayName: "展示名称",
      providerInstanceIds: "供应商渠道",
      actualModels: "已审核部署模型",
      routePolicyId: "路由策略（发布前必填）",
      routeStatus: "路由状态",
      visibilityScope: "可见范围",
      approvalRequired: "需要审批",
      status: "状态",
    },
    requiredFields: [
      "platformModelName",
      "displayName",
      "providerInstanceIds",
      "actualModels",
      "visibilityScope",
    ],
    optionSources: {
      providerInstanceIds: { ...channelSource, multiple: true },
      actualModels: {
        path: "/api/channel-model-deployments",
        label: "providerModelName",
        value: "providerModelName",
        multiple: true,
        dependsOn: "providerInstanceIds",
        filterBy: "providerInstanceId",
        query: { productionStatus: "APPROVED" },
      },
      routePolicyId: { path: "/api/routes", label: "name", value: "id" },
      visibilityScope: { ...tenantSource, multiple: true },
    },
    fieldOptions: {
      visibilityScope: opts([
        ["全部租户", "全部租户"],
        ["内部租户", "内部租户"],
      ]),
      approvalRequired: yesNo,
      routeStatus: opts([
        ["草稿", "DRAFT"],
        ["待审批", "PENDING_APPROVAL"],
        ["已生效", "ACTIVE"],
        ["已停用", "RETIRED"],
        ["路由不存在", "MISSING"],
      ]),
      status,
    },
    fieldTypes: {
      providerInstanceIds: "multiselect",
      actualModels: "multiselect",
      routePolicyId: "select",
      visibilityScope: "multiselect",
      approvalRequired: "select",
    },
    defaultFormValues: { approvalRequired: false },
    builtinActions: ["发布检查", "提交审批", "发布"],
    builtinActionMap: { "发布检查": "GET :id/publish-check", 提交审批: ":id/submit", 发布: "PATCH :id/publish" },
    relatedFields: ["item", "passed", "location", "problem", "action"],
    relatedLabels: { item: "检查项", passed: "结果", location: "异常位置", problem: "异常原因", action: "处理方式" },
  },
  dataSources: {
    title: "数据源管理",
    desc: "管理模型目录、公开资料和价格来源，不直接覆盖生产配置。",
    apiPath: "/api/data-sources",
    allowEdit: false,
    fields: [
      "name",
      "sourceType",
      "endpoint",
      "providerInstanceId",
      "authRef",
      "syncMode",
      "scheduleExpression",
      "nextRunAt",
      "lastSyncAt",
      "lastSyncStatus",
      "status",
      "createdAt",
    ],
    labels: {
      name: "数据源名称",
      sourceType: "来源类型",
      endpoint: "来源地址",
      providerInstanceId: "供应商渠道",
      authRef: "密钥引用",
      config: "受控导入配置",
      syncMode: "同步方式",
      scheduleExpression: "同步周期",
      nextRunAt: "下次执行时间",
      lastSyncAt: "最近同步时间",
      lastSyncStatus: "最近同步状态",
      status: "状态",
      createdAt: "创建时间",
    },
    requiredFields: ["name", "sourceType", "syncMode"],
    editableFields: [
      "name",
      "sourceType",
      "endpoint",
      "providerInstanceId",
      "authRef",
      "config",
      "syncMode",
      "scheduleExpression",
    ],
    optionSources: { providerInstanceId: channelSource },
    fieldOptions: {
      sourceType: opts([
        ["供应商接口", "PROVIDER_API"],
        ["公共参考来源", "PUBLIC_REFERENCE"],
        ["受控文件导入", "FILE_IMPORT"],
      ]),
      syncMode: opts([
        ["手动", "MANUAL"],
        ["定时", "SCHEDULED"],
      ]),
      scheduleExpression: opts([
        ["每十五分钟", "PT15M"],
        ["每小时", "PT1H"],
        ["每六小时", "PT6H"],
        ["每天", "P1D"],
        ["每周", "P7D"],
      ]),
      status,
    },
    fieldTypes: {
      sourceType: "select",
      providerInstanceId: "select",
      config: "json",
      syncMode: "select",
      scheduleExpression: "select",
      status: "select",
    },
    builtinActions: ["立即同步"],
    builtinActionMap: { 立即同步: ":id/sync" },
  },
  syncJobs: {
    title: "同步任务",
    desc: "查看真实同步执行、原始快照、差异数量与失败原因。",
    apiPath: "/api/sync-jobs",
    readonly: true,
    fields: [
      "dataSourceId",
      "jobType",
      "triggerType",
      "status",
      "cursorValue",
      "recordsRead",
      "recordsChanged",
      "errorCode",
      "errorMessage",
      "startedAt",
      "completedAt",
      "createdAt",
    ],
    labels: {
      dataSourceId: "数据源",
      jobType: "任务类型",
      triggerType: "触发方式",
      status: "状态",
      cursorValue: "同步游标",
      recordsRead: "读取记录",
      recordsChanged: "变更记录",
      errorCode: "错误码",
      errorMessage: "错误信息",
      startedAt: "开始时间",
      completedAt: "完成时间",
      createdAt: "创建时间",
    },
    optionSources: {
      dataSourceId: { path: "/api/data-sources", label: "name", value: "id" },
    },
  },
  modelDiscoveries: {
    title: "模型发现",
    desc: "按渠道查看原始模型快照及采集依据。",
    apiPath: "/api/provider-instances",
    readonly: true,
    fields: [
      "instanceName",
      "apiBase",
      "region",
      "lastConnectionTestAt",
      "healthStatus",
      "status",
    ],
    labels: {
      instanceName: "供应商渠道",
      apiBase: "来源地址",
      region: "区域",
      lastConnectionTestAt: "连接测试时间",
      healthStatus: "健康状态",
      status: "状态",
    },
    builtinActions: ["查看快照", "发现模型"],
    builtinActionMap: {
      查看快照: "GET :id/model-snapshots",
      发现模型: ":id/discover-models",
    },
    relatedFields: [
      "sourceEndpoint",
      "httpStatus",
      "checksum",
      "discoveredAt",
      "createdAt",
    ],
  },
  discoveryDiffs: {
    title: "差异审核",
    desc: "对比旧值、新值、来源和影响范围后作出可审计决策。",
    apiPath: "/api/discovery-diffs",
    readonly: true,
    fields: [
      "providerInstanceId",
      "providerModelName",
      "deploymentId",
      "snapshotId",
      "fieldName",
      "oldValue",
      "newValue",
      "source",
      "confidence",
      "decision",
      "decisionReason",
      "decidedBy",
      "decidedAt",
    ],
    labels: {
      providerInstanceId: "供应商渠道",
      providerModelName: "渠道模型",
      deploymentId: "模型部署",
      snapshotId: "原始快照",
      fieldName: "字段",
      oldValue: "旧值",
      newValue: "新值",
      source: "来源",
      confidence: "可信度",
      decision: "审核决定",
      decisionReason: "审核理由",
      decidedBy: "审核人",
      decidedAt: "审核时间",
    },
    builtinActions: ["接受", "忽略", "固定", "回滚"],
    builtinActionMap: {
      接受: "PATCH :id/decision?decision=ACCEPTED",
      忽略: "PATCH :id/decision?decision=IGNORED",
      固定: "PATCH :id/decision?decision=PINNED",
      回滚: ":id/rollback",
    },
  },
  publicPriceReferences: {
    title: "公共价格参考",
    desc: "展示 LiteLLM、models.dev 等公共目录的独立参考价格，仅用于交叉核验，不直接参与生产计费。",
    apiPath: "/api/public-price-references",
    readonly: true,
    fields: [
      "sourceName",
      "adapterCode",
      "providerType",
      "providerModelName",
      "displayName",
      "currency",
      "billingBasis",
      "billingQuantity",
      "region",
      "requestMode",
      "inputUnitPrice",
      "outputUnitPrice",
      "sourceRef",
      "evidenceHash",
      "status",
      "observedAt",
    ],
    labels: {
      sourceName: "参考来源",
      adapterCode: "适配器",
      providerType: "供应商",
      providerModelName: "模型标识",
      displayName: "模型名称",
      currency: "币种",
      billingBasis: "计费对象",
      billingQuantity: "计费基数",
      region: "区域",
      requestMode: "调用模式",
      serviceTier: "服务层级",
      contextTier: "上下文阶梯",
      inputUnitPrice: "输入单位价格（Token 默认每百万）",
      outputUnitPrice: "输出单位价格（Token 默认每百万）",
      priceComponents: "完整价格组件",
      sourceRef: "来源依据",
      evidenceHash: "证据哈希",
      status: "状态",
      observedAt: "最近观测时间",
    },
    fieldOptions: {
      billingBasis: opts([
        ["Token", "TOKEN"],
        ["请求", "REQUEST"],
        ["图片", "IMAGE"],
        ["秒", "SECOND"],
        ["分钟", "MINUTE"],
        ["字符", "CHARACTER"],
        ["音频分钟", "AUDIO_MINUTE"],
      ]),
      status: opts([
        ["有效", "ACTIVE"],
        ["来源中缺失", "MISSING"],
        ["存在争议", "DISPUTED"],
      ]),
    },
    builtinActions: ["查看价格组件"],
    builtinActionMap: { 查看价格组件: "GET :id" },
    relatedFields: ["priceComponents", "sourceRef", "evidenceHash", "serviceTier", "contextTier"],
    emptyTitle: "尚无公共价格参考",
    emptyDescription: "请在价格源管理中启用 LiteLLM 或 models.dev 参考源并执行同步。",
  },
  providerPriceSources: {
    title: "价格源管理",
    desc: "配置公共参考源与供应商官方价格源，自动获取原始价格并按规则更新。",
    apiPath: "/api/provider-price-sources",
    columnWidths: { name: "190px", updatedAt: "120px" },
    fields: [
      "name",
      "providerType",
      "endpoint",
      "region",
      "defaultCurrency",
      "scheduleExpression",
      "maxAutoChangeRatio",
      "confirmationRuns",
      "fetchMode",
      "sourcePriority",
      "priceNature",
      "status",
      "pendingDiffCount",
      "updatedAt",
    ],
    detailFields: [
      "name",
      "sourceClass",
      "adapterCode",
      "providerType",
      "authMode",
      "providerInstanceId",
      "endpoint",
      "officialHosts",
      "region",
      "defaultCurrency",
      "scheduleExpression",
      "autoPublish",
      "maxAutoChangeRatio",
      "confirmationRuns",
      "fetchMode",
      "sourcePriority",
      "priceNature",
      "structureFingerprint",
      "parseStatus",
      "sourceEvidence",
      "config",
      "status",
      "lastSuccessAt",
      "lastFailureAt",
      "lastError",
      "pendingDiffCount",
      "updatedAt",
    ],
    labels: {
      name: "价格源名称",
      sourceClass: "价格源类别",
      adapterCode: "适配器",
      providerType: "供应商类型",
      authMode: "认证方式",
      providerInstanceId: "认证供应商渠道",
      endpoint: "官方来源地址",
      officialHosts: "官方域名",
      region: "价格区域",
      defaultCurrency: "默认币种",
      scheduleExpression: "同步周期",
      autoPublish: "低风险自动发布",
      maxAutoChangeRatio: "最大自动变动比例",
      confirmationRuns: "连续确认次数",
      fetchMode: "获取模式",
      sourcePriority: "来源优先级",
      priceNature: "价格性质",
      structureFingerprint: "页面结构指纹",
      parseStatus: "解析状态",
      sourceEvidence: "解析诊断信息",
      config: "适配器配置",
      status: "状态",
      lastSuccessAt: "最近成功时间",
      lastFailureAt: "最近失败时间",
      lastError: "最近错误",
      pendingDiffCount: "待审核差异",
      updatedAt: "更新时间",
    },
    requiredFields: [
      "name",
      "sourceClass",
      "adapterCode",
      "authMode",
      "endpoint",
      "officialHosts",
      "region",
      "defaultCurrency",
      "scheduleExpression",
      "maxAutoChangeRatio",
      "confirmationRuns",
      "fetchMode",
      "sourcePriority",
      "priceNature",
    ],
    editableFields: [
      "name",
      "sourceClass",
      "adapterCode",
      "providerType",
      "authMode",
      "providerInstanceId",
      "endpoint",
      "officialHosts",
      "region",
      "defaultCurrency",
      "scheduleExpression",
      "autoPublish",
      "maxAutoChangeRatio",
      "confirmationRuns",
      "fetchMode",
      "sourcePriority",
      "priceNature",
      "config",
    ],
    updateMethod: "patch",
    compactForm: true,
    numberFields: ["maxAutoChangeRatio", "confirmationRuns", "sourcePriority", "pendingDiffCount"],
    optionSources: {
      providerType: {
        path: "/api/provider-templates",
        label: "providerName",
        value: "providerType",
      },
      providerInstanceId: {
        path: "/api/provider-instances",
        label: "instanceName",
        value: "id",
      },
    },
    fieldOptions: {
      sourceClass: opts([
        ["公共参考来源", "PUBLIC_REFERENCE"],
        ["供应商官方价格", "OFFICIAL"],
      ]),
      adapterCode: opts([
        ["LiteLLM 成本参考表", "LITELLM_COST_MAP"],
        ["models.dev 公共参考", "MODELS_DEV"],
        ["Azure Retail Prices API", "AZURE_RETAIL_PRICES"],
        ["AWS Price List Bulk", "AWS_PRICE_LIST_BULK"],
        ["Google Cloud Billing Catalog", "GOOGLE_CLOUD_CATALOG"],
        ["通用价格文档（HTML/CSV/JSON/PDF）", "GENERIC_DOCUMENT"],
        ["DeepSeek 官方价格页", "DEEPSEEK_OFFICIAL_PAGE"],
        ["千问中国内地官方价格页", "QWEN_OFFICIAL_PAGE"],
        ["Kimi 中国站官方价格页", "KIMI_OFFICIAL_PAGE"],
        ["Xiaomi MiMo 中国区官方价格页", "XIAOMI_MIMO_OFFICIAL_PAGE"],
        ["智谱中国区官方价格页", "ZHIPU_OFFICIAL_PAGE"],
        ["供应商官方 JSON", "OFFICIAL_JSON"],
        ["供应商官方 CSV", "OFFICIAL_CSV"],
      ]),
      authMode: opts([
        ["无需认证", "NONE"],
        ["复用供应商渠道凭据", "PROVIDER_INSTANCE"],
      ]),
      region: opts([
        ["全球", "global"],
        ["中国", "cn"],
        ["美国", "us"],
        ["欧洲", "eu"],
        ["亚太", "apac"],
      ]),
      defaultCurrency: opts([
        ["人民币", "CNY"],
        ["美元", "USD"],
        ["欧元", "EUR"],
      ]),
      scheduleExpression: opts([
        ["每十五分钟", "PT15M"],
        ["每小时", "PT1H"],
        ["每六小时", "PT6H"],
        ["每天", "P1D"],
        ["每周", "P7D"],
      ]),
      autoPublish: yesNo,
      fetchMode: opts([
        ["自动选择", "AUTO"],
        ["结构化 HTTP API", "STRUCTURED_HTTP"],
        ["静态 HTML / 文档", "STATIC_HTML"],
        ["无头浏览器", "HEADLESS"],
      ]),
      priceNature: opts([
        ["官方原价", "ORIGINAL"],
        ["促销价", "PROMOTIONAL"],
        ["免费额度", "FREE_QUOTA"],
      ]),
      status: opts([
        ["草稿", "DRAFT"],
        ["启用", "ACTIVE"],
        ["暂停", "PAUSED"],
        ["异常", "DEGRADED"],
        ["停用", "DISABLED"],
      ]),
    },
    fieldPresets: {
      adapterCode: {
        AZURE_RETAIL_PRICES: {
          sourceClass: "OFFICIAL",
          authMode: "NONE",
          officialHosts: "prices.azure.com",
          defaultCurrency: "USD",
          fetchMode: "STRUCTURED_HTTP",
          autoPublish: false,
          config: {
            includePattern: "(?i)azure openai|openai",
            modelPattern: "(?i)\\b(?<model>(?:gpt|o[134])[-a-z0-9.]+)\\b",
            maxPages: 20,
            maxResponseBytes: 10000000,
          },
        },
        AWS_PRICE_LIST_BULK: {
          sourceClass: "OFFICIAL",
          authMode: "NONE",
          endpoint: "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonBedrock/current/index.json",
          officialHosts: "pricing.us-east-1.amazonaws.com",
          defaultCurrency: "USD",
          fetchMode: "STRUCTURED_HTTP",
          autoPublish: false,
          config: {
            includePattern: "(?i)bedrock|foundation model|model inference",
            modelPattern: "(?i)\\b(?<model>(?:claude|nova|titan|llama|mistral|command|jamba)[-a-z0-9._:]*)\\b",
            maxResponseBytes: 50000000,
          },
        },
        GOOGLE_CLOUD_CATALOG: {
          sourceClass: "OFFICIAL",
          authMode: "PROVIDER_INSTANCE",
          officialHosts: "cloudbilling.googleapis.com",
          defaultCurrency: "USD",
          fetchMode: "STRUCTURED_HTTP",
          autoPublish: false,
          config: {
            authHeader: "x-goog-api-key",
            includePattern: "(?i)vertex ai|generative ai|gemini",
            modelPattern: "(?i)\\b(?<model>gemini[-a-z0-9.]+)\\b",
            maxPages: 20,
            maxResponseBytes: 15000000,
          },
        },
        GENERIC_DOCUMENT: {
          sourceClass: "OFFICIAL",
          authMode: "NONE",
          fetchMode: "AUTO",
          autoPublish: false,
          config: {
            recordsPath: "data",
            modelField: "model",
            displayNameField: "display_name",
            inputField: "input",
            outputField: "output",
            cacheReadField: "cache_read",
            cacheWriteField: "cache_write",
            currencyField: "currency",
            billingQuantityField: "billing_quantity",
            sourceBillingQuantity: 1000000,
            llmEnabled: false,
          },
        },
      },
    },
    fieldTypes: {
      sourceClass: "select",
      adapterCode: "select",
      providerType: "select",
      authMode: "select",
      providerInstanceId: "select",
      officialHosts: "host-list",
      region: "select",
      defaultCurrency: "select",
      scheduleExpression: "select",
      autoPublish: "select",
      fetchMode: "select",
      priceNature: "select",
      config: "json",
      status: "select",
    },
    defaultFormValues: {
      sourceClass: "PUBLIC_REFERENCE",
      adapterCode: "LITELLM_COST_MAP",
      authMode: "NONE",
      officialHosts: "",
      region: "global",
      defaultCurrency: "USD",
      scheduleExpression: "P1D",
      autoPublish: false,
      maxAutoChangeRatio: 0.3,
      confirmationRuns: 1,
      fetchMode: "AUTO",
      sourcePriority: 100,
      priceNature: "ORIGINAL",
      config: {},
      status: "DRAFT",
    },
    builtinActions: ["测试获取", "测试解析", "同步", "启用", "暂停"],
    builtinActionMap: {
      测试获取: ":id/test",
      测试解析: "POST_SHOW :id/test-parse",
      同步: ":id/sync",
      启用: ":id/enable",
      暂停: ":id/pause",
    },
    relatedFields: [
      "httpStatus",
      "contentType",
      "responseBytes",
      "parseStatus",
      "tableCount",
      "matchedTableCount",
      "skippedTableCount",
      "recordsNormalized",
      "structureFingerprint",
      "sourceEvidence",
      "warnings",
      "headlessRecommended",
      "discoveredPricePages",
      "sample",
    ],
    relatedLabels: {
      httpStatus: "HTTP 状态",
      contentType: "内容类型",
      responseBytes: "响应字节数",
      parseStatus: "解析状态",
      tableCount: "页面表格数",
      matchedTableCount: "匹配价格表",
      skippedTableCount: "跳过表格数",
      recordsNormalized: "生成价格记录",
      structureFingerprint: "结构指纹",
      sourceEvidence: "解析诊断",
      warnings: "解析警告",
      headlessRecommended: "建议使用无头浏览器",
      discoveredPricePages: "发现的官方定价子页面",
      sample: "标准化样例",
    },
    emptyTitle: "尚未配置价格源",
    emptyDescription: "可启用内置 LiteLLM/models.dev 参考源，或新增供应商官方 JSON/CSV 价格源。",
  },
  providerPriceSyncRuns: {
    title: "价格同步任务",
    desc: "查看价格获取、标准化、差异和发布结果。",
    apiPath: "/api/provider-price-sync-runs",
    readonly: true,
    fields: [
      "sourceName",
      "sourceClass",
      "adapterCode",
      "triggerType",
      "status",
      "parseStatus",
      "httpStatus",
      "recordsFetched",
      "recordsNormalized",
      "generatedPriceCount",
      "recordsChanged",
      "recordsAutoPublished",
      "recordsReviewRequired",
      "errorCode",
      "errorMessage",
      "startedAt",
      "completedAt",
    ],
    labels: {
      sourceName: "价格源",
      sourceClass: "来源类别",
      adapterCode: "适配器",
      triggerType: "触发方式",
      status: "状态",
      parseStatus: "解析状态",
      httpStatus: "HTTP 状态",
      recordsFetched: "获取记录",
      recordsNormalized: "标准化记录",
      parsedTableCount: "页面表格数",
      matchedTableCount: "匹配价格表",
      generatedPriceCount: "生成价格记录",
      diagnosticSnapshot: "解析诊断快照",
      recordsChanged: "变更记录",
      recordsAutoPublished: "自动发布",
      recordsReviewRequired: "待审核",
      errorCode: "错误码",
      errorMessage: "错误信息",
      startedAt: "开始时间",
      completedAt: "完成时间",
      executionLog: "执行日志",
      snapshots: "原始快照",
      diffs: "价格差异",
    },
    fieldOptions: {
      parseStatus: opts([
        ["解析成功", "PRICE_PARSED"],
        ["价格表已匹配但无记录", "PRICE_TABLE_MATCHED_NO_RECORDS"],
        ["未匹配价格表", "PRICE_TABLE_NOT_MATCHED"],
        ["未发现价格表", "NO_PRICE_TABLE"],
        ["内容未变化，未重新解析", "NOT_PARSED_UNCHANGED"],
        ["尚未解析", "NOT_PARSED"],
      ]),
      status: opts([
        ["待执行", "PENDING"],
        ["执行中", "RUNNING"],
        ["执行成功", "SUCCEEDED"],
        ["无价格变化", "NO_CHANGE"],
        ["待审核", "REVIEW_REQUIRED"],
        ["执行失败", "FAILED"],
        ["已取消", "CANCELLED"],
      ]),
    },
    builtinActions: ["查看执行详情"],
    builtinActionMap: { 查看执行详情: "GET :id" },
    relatedFields: [
      "parseStatus",
      "parsedTableCount",
      "matchedTableCount",
      "generatedPriceCount",
      "diagnosticSnapshot",
      "executionLog",
      "snapshots",
      "diffs",
    ],
  },
  providerPriceSnapshots: {
    title: "价格原始快照",
    desc: "保留官方响应、来源地址、哈希、解析器版本和获取时间，支撑审计与回放。",
    apiPath: "/api/provider-price-snapshots",
    readonly: true,
    fields: [
      "sourceName",
      "sourceEndpoint",
      "finalEndpoint",
      "httpStatus",
      "contentType",
      "checksum",
      "responseBytes",
      "parserVersion",
      "fetchedAt",
    ],
    labels: {
      sourceName: "价格源",
      sourceEndpoint: "来源地址",
      finalEndpoint: "最终地址",
      httpStatus: "HTTP 状态",
      contentType: "内容类型",
      checksum: "SHA-256",
      responseBytes: "响应字节数",
      parserVersion: "解析器版本",
      fetchedAt: "获取时间",
      rawContent: "原始内容",
      etag: "ETag",
      lastModified: "最后修改时间",
    },
    builtinActions: ["查看原始内容"],
    builtinActionMap: { 查看原始内容: "GET :id" },
    relatedFields: ["sourceEndpoint", "finalEndpoint", "etag", "lastModified", "checksum", "rawContent"],
  },
  providerPriceDiffs: {
    title: "价格差异审核",
    desc: "低风险变化可自动发布；高风险变化保留旧价格并等待审核。",
    apiPath: "/api/provider-price-diffs",
    readonly: true,
    defaultSort: "createdAt",
    defaultOrder: "desc",
    fields: [
      "sourceName",
      "providerType",
      "providerModelName",
      "region",
      "requestMode",
      "serviceTier",
      "contextTier",
      "diffType",
      "changeRatio",
      "riskLevel",
      "confirmationProgress",
      "status",
      "decidedByName",
      "decidedAt",
      "createdAt",
    ],
    detailFields: [
      "sourceName",
      "providerType",
      "providerModelName",
      "region",
      "requestMode",
      "serviceTier",
      "contextTier",
      "diffType",
      "oldValue",
      "newValue",
      "changeRatio",
      "riskLevel",
      "confirmationCount",
      "confirmationRequired",
      "lastConfirmedAt",
      "status",
      "decisionReason",
      "decidedByName",
      "decidedAt",
      "publishedCatalogId",
      "createdAt",
    ],
    labels: {
      sourceName: "价格源",
      providerType: "供应商",
      providerModelName: "供应商模型",
      region: "区域",
      requestMode: "调用模式",
      serviceTier: "服务层级",
      contextTier: "上下文阶梯",
      diffType: "差异类型",
      oldValue: "旧价格",
      newValue: "新价格",
      changeRatio: "变化比例",
      riskLevel: "风险等级",
      confirmationProgress: "连续确认",
      confirmationCount: "已确认次数",
      confirmationRequired: "要求确认次数",
      lastConfirmedAt: "最近确认时间",
      status: "审核状态",
      decisionReason: "审核意见",
      decidedByName: "审核人",
      decidedAt: "审核时间",
      publishedCatalogId: "发布目录记录",
      createdAt: "发现时间",
    },
    fieldOptions: {
      diffType: opts([
        ["新增模型", "MODEL_ADDED"],
        ["模型疑似移除", "MODEL_REMOVED"],
        ["价格变化", "PRICE_CHANGED"],
        ["币种变化", "CURRENCY_CHANGED"],
        ["计费单位变化", "UNIT_CHANGED"],
        ["计费维度变化", "BILLING_DIMENSION_CHANGED"],
        ["区域变化", "REGION_CHANGED"],
        ["模型映射变化", "MODEL_MAPPING_CHANGED"],
        ["来源结构变化", "SOURCE_STRUCTURE_CHANGED"],
      ]),
      riskLevel: opts([
        ["低", "LOW"],
        ["中", "MEDIUM"],
        ["高", "HIGH"],
        ["严重", "CRITICAL"],
      ]),
      status: opts([
        ["待审核", "PENDING"],
        ["已自动发布", "AUTO_PUBLISHED"],
        ["已批准", "APPROVED"],
        ["已驳回", "REJECTED"],
        ["已忽略", "IGNORED"],
        ["已撤销", "REVOKED"],
      ]),
    },
    builtinActions: ["查看差异", "批准发布", "驳回", "撤销发布"],
    builtinActionMap: {
      查看差异: "GET :id",
      批准发布: ":id/approve",
      驳回: ":id/reject",
      撤销发布: ":id/revoke",
    },
    actionForms: {
      撤销发布: {
        fields: ["reason"],
        labels: { reason: "撤销原因" },
        requiredFields: ["reason"],
        fieldTypes: { reason: "textarea" },
      },
    },
    relatedFields: ["oldValue", "newValue", "publishedCatalogId"],
  },
  providerPriceCatalog: {
    title: "供应商官方价格目录",
    desc: "默认按每百万 Token 维护缓存未命中输入、缓存命中输入、缓存写入和输出价格；长上下文、TTL 等变体使用高级组件数组维护。",
    descNoWrap: true,
    apiPath: "/api/provider-price-catalog",
    defaultSort: "effectiveFrom",
    defaultOrder: "desc",
    sortFallbackFields: ["updatedAt"],
    fields: [
      "providerType",
      "providerModelName",
      "currency",
      "cacheReadMode",
      "inputUnitPrice",
      "cacheReadUnitPrice",
      "cacheWriteUnitPrice",
      "outputUnitPrice",
      "priceCompletenessStatus",
      "status",
      "matchedDeployments",
      "updatedAt",
    ],
    detailFields: [
      "providerType",
      "providerModelName",
      "displayName",
      "aliases",
      "currency",
      "billingBasis",
      "billingQuantity",
      "inputUnitPrice",
      "cacheReadUnitPrice",
      "cacheReadMode",
      "cacheWriteUnitPrice",
      "cacheWriteMode",
      "outputUnitPrice",
      "priceComponents",
      "componentSchemaVersion",
      "cacheWriteVariantCount",
      "priceCompletenessStatus",
      "cachePricingStatus",
      "sourceType",
      "sourceRef",
      "sourceConfidence",
      "sourceUpdatedAt",
      "effectiveFrom",
      "effectiveTo",
      "revision",
      "status",
      "matchedDeployments",
      "updatedAt",
    ],
    labels: {
      providerType: "供应商类型",
      providerModelName: "供应商模型名",
      displayName: "展示名称",
      aliases: "模型别名",
      currency: "币种",
      billingBasis: "计费对象",
      billingQuantity: "计费基数",
      inputUnitPrice: "输入价格（缓存未命中）",
      cacheReadUnitPrice: "输入价格（缓存命中）",
      cacheReadMode: "缓存命中价格模式",
      cacheWriteUnitPrice: "输入价格（缓存写入）",
      cacheWriteMode: "缓存写入价格模式",
      outputUnitPrice: "输出价格",
      priceComponents: "高级价格组件（JSON 数组）",
      componentSchemaVersion: "组件结构版本",
      cacheWriteVariantCount: "缓存写入变体数",
      priceCompletenessStatus: "价格完整性",
      cachePricingStatus: "缓存价格状态",
      sourceType: "来源类型",
      sourceRef: "来源依据",
      sourceConfidence: "来源可信度",
      sourceUpdatedAt: "来源更新时间",
      effectiveFrom: "生效时间",
      effectiveTo: "失效时间",
      revision: "目录版本",
      status: "状态",
      matchedDeployments: "已匹配部署",
      updatedAt: "更新时间",
    },
    requiredFields: [
      "providerType",
      "providerModelName",
      "currency",
      "billingBasis",
      "billingQuantity",
      "inputUnitPrice",
      "cacheReadMode",
      "cacheWriteMode",
      "outputUnitPrice",
      "sourceType",
      "sourceRef",
      "effectiveFrom",
    ],
    editableFields: [
      "providerType",
      "providerModelName",
      "aliases",
      "currency",
      "billingBasis",
      "billingQuantity",
      "inputUnitPrice",
      "cacheReadUnitPrice",
      "cacheReadMode",
      "cacheWriteUnitPrice",
      "cacheWriteMode",
      "outputUnitPrice",
      "priceComponents",
      "sourceType",
      "sourceRef",
      "sourceConfidence",
      "sourceUpdatedAt",
      "effectiveFrom",
      "effectiveTo",
      "status",
      "approvalStatus",
    ],
    updateMethod: "patch",
    numberFields: [
      "billingQuantity",
      "inputUnitPrice",
      "cacheReadUnitPrice",
      "cacheWriteUnitPrice",
      "outputUnitPrice",
      "sourceConfidence",
    ],
    optionSources: {
      providerType: {
        path: "/api/provider-templates",
        label: "providerName",
        value: "providerType",
      },
    },
    fieldOptions: {
      currency: opts([["CNY", "CNY"]]),
      billingBasis: opts([
        ["Token", "TOKEN"],
        ["请求", "REQUEST"],
        ["图片", "IMAGE"],
        ["秒", "SECOND"],
        ["分钟", "MINUTE"],
        ["字符", "CHARACTER"],
        ["音频分钟", "AUDIO_MINUTE"],
      ]),
      cacheReadMode: opts([
        ["明确价格", "EXPLICIT"],
        ["明确免费", "EXPLICIT_ZERO"],
        ["沿用缓存未命中输入价", "INHERIT_INPUT"],
        ["不适用", "NOT_APPLICABLE"],
        ["尚未确认", "UNKNOWN"],
      ]),
      cacheWriteMode: opts([
        ["明确价格", "EXPLICIT"],
        ["明确免费", "EXPLICIT_ZERO"],
        ["沿用缓存未命中输入价", "INHERIT_INPUT"],
        ["不适用", "NOT_APPLICABLE"],
        ["尚未确认", "UNKNOWN"],
      ]),
      priceCompletenessStatus: opts([
        ["完整", "COMPLETE"],
        ["部分缺失", "PARTIAL"],
        ["缓存价格未确认", "UNKNOWN_CACHE_PRICE"],
        ["模型不支持缓存", "UNSUPPORTED_CACHE"],
      ]),
      cachePricingStatus: opts([
        ["完整", "COMPLETE"],
        ["部分缺失", "PARTIAL"],
        ["缓存价格未确认", "UNKNOWN_CACHE_PRICE"],
        ["模型不支持缓存", "UNSUPPORTED_CACHE"],
      ]),
      sourceType: opts([
        ["供应商官方公开价", "OFFICIAL_REFERENCE"],
        ["供应商价格接口", "PROVIDER_API"],
        ["人工核验官方价", "MANUAL_VERIFIED"],
      ]),
      status: opts([
        ["启用", "ACTIVE"],
        ["停用", "INACTIVE"],
      ]),
    },
    fieldTypes: {
      providerType: "select",
      aliases: "aliases",
      currency: "select",
      billingBasis: "select",
      cacheReadMode: "select",
      cacheWriteMode: "select",
      priceComponents: "json",
      sourceType: "select",
      sourceUpdatedAt: "datetime",
      effectiveFrom: "datetime",
      effectiveTo: "datetime",
      status: "select",
    },
    defaultFormValues: {
      currency: "CNY",
      billingBasis: "TOKEN",
      billingQuantity: 1000000,
      cacheReadMode: "UNKNOWN",
      cacheWriteMode: "UNKNOWN",
      priceComponents: "[]",
      sourceType: "OFFICIAL_REFERENCE",
      sourceConfidence: 1,
      status: "ACTIVE",
    },
    builtinActions: ["重新匹配"],
    builtinActionMap: { 重新匹配: ":id/rematch" },
    emptyTitle: "尚未维护供应商官方价格",
    emptyDescription: "新增或同步官方价格后，系统会自动匹配已发现模型并生成生效价格版本。",
  },
  priceVersions: {
    title: "模型生效价格",
    desc: "展示模型部署实际使用的缓存感知价格版本，包括缓存未命中、缓存命中、缓存写入、输出及高级变体。",
    apiPath: "/api/price-versions",
    readonly: true,
    fields: [
      "providerType",
      "instanceName",
      "providerModelName",
      "currency",
      "inputUnitPrice",
      "cacheReadUnitPrice",
      "cacheReadMode",
      "cacheWriteUnitPrice",
      "outputUnitPrice",
      "priceCompletenessStatus",
      "version",
      "status",
    ],
    detailFields: [
      "providerType",
      "instanceName",
      "providerModelName",
      "modelDisplayName",
      "currency",
      "billingBasis",
      "billingQuantity",
      "inputUnitPrice",
      "cacheReadUnitPrice",
      "cacheReadMode",
      "cacheWriteUnitPrice",
      "cacheWriteMode",
      "outputUnitPrice",
      "priceComponents",
      "componentSchemaVersion",
      "cacheWriteVariantCount",
      "priceCompletenessStatus",
      "sourceType",
      "sourceRef",
      "matchType",
      "autoGenerated",
      "version",
      "effectiveFrom",
      "effectiveTo",
      "status",
    ],
    labels: {
      providerType: "供应商类型",
      instanceName: "供应商渠道",
      providerModelName: "供应商模型",
      modelDisplayName: "模型名称",
      currency: "币种",
      billingBasis: "计费对象",
      billingQuantity: "计费基数",
      inputUnitPrice: "输入价格（缓存未命中）",
      cacheReadUnitPrice: "输入价格（缓存命中）",
      cacheReadMode: "缓存命中价格模式",
      cacheWriteUnitPrice: "输入价格（缓存写入）",
      cacheWriteMode: "缓存写入价格模式",
      outputUnitPrice: "输出价格",
      priceComponents: "完整价格组件",
      componentSchemaVersion: "组件结构版本",
      cacheWriteVariantCount: "缓存写入变体数",
      priceCompletenessStatus: "价格完整性",
      sourceType: "来源类型",
      sourceRef: "来源依据",
      matchType: "匹配方式",
      autoGenerated: "自动生成",
      version: "价格版本",
      effectiveFrom: "生效时间",
      effectiveTo: "失效时间",
      status: "状态",
      approvalStatus: "审批状态",
    },
    numberFields: [
      "version",
      "billingQuantity",
      "inputUnitPrice",
      "cacheReadUnitPrice",
      "cacheWriteUnitPrice",
      "outputUnitPrice",
    ],
    fieldOptions: {
      currency: opts([["CNY", "CNY"]]),
      billingBasis: opts([
        ["Token", "TOKEN"],
        ["请求", "REQUEST"],
        ["图片", "IMAGE"],
        ["秒", "SECOND"],
        ["分钟", "MINUTE"],
        ["字符", "CHARACTER"],
        ["音频分钟", "AUDIO_MINUTE"],
      ]),
      cacheReadMode: opts([
        ["明确价格", "EXPLICIT"],
        ["明确免费", "EXPLICIT_ZERO"],
        ["沿用缓存未命中输入价", "INHERIT_INPUT"],
        ["不适用", "NOT_APPLICABLE"],
        ["尚未确认", "UNKNOWN"],
      ]),
      cacheWriteMode: opts([
        ["明确价格", "EXPLICIT"],
        ["明确免费", "EXPLICIT_ZERO"],
        ["沿用缓存未命中输入价", "INHERIT_INPUT"],
        ["不适用", "NOT_APPLICABLE"],
        ["尚未确认", "UNKNOWN"],
      ]),
      priceCompletenessStatus: opts([
        ["完整", "COMPLETE"],
        ["部分缺失", "PARTIAL"],
        ["缓存价格未确认", "UNKNOWN_CACHE_PRICE"],
        ["模型不支持缓存", "UNSUPPORTED_CACHE"],
      ]),
      sourceType: opts([
        ["供应商官方公开价", "OFFICIAL_REFERENCE"],
        ["供应商价格接口", "PROVIDER_API"],
        ["人工核验官方价", "MANUAL_VERIFIED"],
      ]),
      matchType: opts([
        ["精确匹配", "EXACT"],
        ["别名匹配", "ALIAS"],
        ["人工匹配", "MANUAL"],
      ]),
      autoGenerated: yesNo,
      status,
    },
    emptyTitle: "尚未生成模型价格",
    emptyDescription: "请先维护供应商官方价格目录并执行模型发现，系统会自动匹配并生成生效价格版本。",
  },
  budgetRules: {
    title: "预算管理",
    desc: "配置预算范围、预警阈值与超限动作，并读取真实执行状态。",
    apiPath: "/api/budget-rules",
    fields: [
      "scopeType",
      "scopeId",
      "currency",
      "amountLimit",
      "warningThresholdPercent",
      "overLimitAction",
      "degradeModelAlias",
      "effectiveFrom",
      "effectiveTo",
      "status",
    ],
    allowEdit: false,
    labels: {
      scopeType: "预算范围",
      scopeId: "范围对象 ID",
      currency: "币种",
      amountLimit: "预算额度",
      warningThresholdPercent: "预警阈值（%）",
      overLimitAction: "超限动作",
      degradeModelAlias: "降级服务模型",
      effectiveFrom: "生效时间",
      effectiveTo: "失效时间",
      status: "状态",
    },
    requiredFields: [
      "scopeType",
      "scopeId",
      "currency",
      "amountLimit",
      "warningThresholdPercent",
      "overLimitAction",
    ],
    numberFields: ["amountLimit", "warningThresholdPercent"],
    optionSources: {
      scopeId: {
        path: "/api/tenants",
        pathsByValue: {
          TENANT: "/api/tenants",
          PROJECT: "/api/projects",
          APP: "/api/apps",
          API_KEY: "/api/keys",
        },
        dependsOn: "scopeType",
        label: "name",
        value: "id",
      },
      degradeModelAlias: {
        path: "/api/platform-models",
        label: "displayName",
        value: "platformModelName",
      },
    },
    fieldOptions: {
      scopeType: opts([
        ["租户", "TENANT"],
        ["项目", "PROJECT"],
        ["应用", "APP"],
        ["API Key", "API_KEY"],
      ]),
      currency: opts([["人民币", "CNY"]]),
      overLimitAction: opts([
        ["拒绝请求", "BLOCK"],
        ["仅告警", "ALERT_ONLY"],
        ["降级模型", "DEGRADE"],
      ]),
      status,
    },
    fieldTypes: {
      scopeType: "select",
      scopeId: "select",
      currency: "select",
      overLimitAction: "select",
      degradeModelAlias: "select",
      effectiveFrom: "datetime",
      effectiveTo: "datetime",
    },
    builtinActions: ["提交审批", "审批后生效", "退役", "查看版本"],
    builtinActionMap: {
      提交审批: ":id/submit",
      审批后生效: ":id/activate",
      退役: ":id/retire",
      查看版本: "GET :id/versions",
    },
    actionForms: {
      提交审批: {
        fields: ["decisionReason"],
        labels: { decisionReason: "提交理由" },
        requiredFields: ["decisionReason"],
      },
    },
    relatedFields: ["version", "sourceAction", "createdBy", "createdAt"],
    relatedLabels: {
      version: "版本号",
      sourceAction: "来源动作",
      createdBy: "提交人",
      createdAt: "提交时间",
    },
  },
  costStatements: {
    title: "内部成本单",
    desc: "按组织、项目、应用、Key、模型和渠道汇总本月真实成本。",
    apiPath: `/api/cost-statements?from=${encodeURIComponent(statementFrom)}&to=${encodeURIComponent(statementTo)}`,
    readonly: true,
    fields: [
      "tenantId",
      "projectId",
      "appId",
      "apiKeyId",
      "modelAlias",
      "providerId",
      "requestCount",
      "totalTokens",
      "actualCost",
      "currency",
    ],
    labels: {
      tenantId: "租户",
      projectId: "项目",
      appId: "应用",
      apiKeyId: "API Key",
      modelAlias: "模型",
      providerId: "供应商渠道",
      requestCount: "请求数",
      totalTokens: "Token",
      actualCost: "实际成本",
      currency: "币种",
    },
  },
  providerHealth: {
    title: "渠道健康",
    internalScroll: true,
    desc: "读取渠道连接测试、最近成功时间和模型可用性。",
    apiPath: "/api/provider-instances",
    readonly: true,
    defaultSort: "lastConnectionTestAt",
    defaultOrder: "desc",
    fields: [
      "instanceName",
      "region",
      "lastConnectionTestStatus",
      "lastConnectionTestAt",
      "healthStatus",
      "enabledModels",
      "status",
    ],
    detailFields: providerChannelDetailFields,
    detailSections: providerChannelDetailSections,
    labels: {
      instanceName: "供应商渠道",
      region: "区域",
      lastConnectionTestStatus: "连接测试",
      lastConnectionTestAt: "测试时间",
      healthStatus: "健康状态",
      enabledModels: "启用模型",
      providerTemplateId: "供应商模板",
      apiStyle: "协议",
      apiBase: "API 地址",
      environment: "环境",
      owner: "负责人",
      rateLimitRpm: "每分钟请求",
      rateLimitTpm: "每分钟 Token",
      keyStatus: "密钥状态",
      lastConnectionTestError: "异常原因",
      lastConnectionTestHost: "测试目标主机",
      lastConnectionTestPort: "测试目标端口",
      status: "状态",
    },
    builtinActions: ["连接测试"],
    builtinActionMap: { 连接测试: ":id/test-connection" },
  },
  alerts: {
    title: "告警",
    internalScroll: true,
    desc: "处理模型消失、能力失败、预算和成本异常等真实事件。",
    apiPath: "/api/alerts",
    readonly: true,
    defaultSort: "createdAt",
    defaultOrder: "desc",
    fields: [
      "alertType",
      "severity",
      "resourceType",
      "resourceId",
      "title",
      "status",
      "acknowledgedBy",
      "acknowledgedAt",
      "resolvedBy",
      "createdAt",
      "resolvedAt",
    ],
    detailFields: [
      "alertType",
      "severity",
      "resourceType",
      "resourceId",
      "title",
      "detail",
      "status",
      "acknowledgedBy",
      "acknowledgedAt",
      "resolvedBy",
      "resolvedAt",
      "createdAt",
    ],
    labels: {
      alertType: "告警类型",
      severity: "级别",
      resourceType: "对象类型",
      resourceId: "对象 ID",
      title: "告警标题",
      detail: "详情",
      status: "状态",
      acknowledgedBy: "确认人",
      acknowledgedAt: "确认时间",
      resolvedBy: "解决人",
      resolvedAt: "解决时间",
      createdAt: "发生时间",
    },
    fieldOptions: {
      alertType: opts([
        ["模型缺少正式价格", "MODEL_PRICE_MISSING"],
        ["缓存价格缺失", "CACHE_PRICE_MISSING"],
        ["价格源同步失败", "PRICE_SOURCE_SYNC_FAILED"],
        ["供应商价格覆盖缺口", "PROVIDER_PRICE_COVERAGE_GAP"],
        ["模型疑似消失", "MODEL_DISCOVERY_MISSING_SUSPECTED"],
        ["模型目录不一致", "MODEL_DIRECTORY_INCONSISTENT"],
        ["模型已消失", "MODEL_DISAPPEARED"],
      ]),
      resourceType: opts([
        ["模型部署", "MODEL_DEPLOYMENT"],
        ["价格源", "PRICE_SOURCE"],
        ["供应商渠道", "PROVIDER_INSTANCE"],
        ["企业服务模型", "PLATFORM_MODEL"],
        ["预算规则", "BUDGET_RULE"],
        ["API Key", "API_KEY"],
      ]),
      severity: opts([
        ["严重", "CRITICAL"],
        ["高", "HIGH"],
        ["警告", "WARNING"],
        ["信息", "INFO"],
      ]),
      status: opts([
        ["待处理", "OPEN"],
        ["已确认", "ACKNOWLEDGED"],
        ["已解决", "RESOLVED"],
      ]),
    },
    builtinActions: ["确认", "解决"],
    builtinActionMap: {
      确认: "PATCH :id/acknowledge",
      解决: "PATCH :id/resolve",
    },
  },
  audit: {
    title: "操作审计",
    desc: "查询价格、路由、模型、Key、预算和敏感查看的完整审计轨迹。",
    apiPath: "/api/audit",
    readonly: true,
    internalScroll: true,
    defaultSort: "createdAt",
    defaultOrder: "desc",
    columnWidths: {
      createdAt: "180px",
      actorName: "120px",
      action: "190px",
      objectType: "130px",
      objectName: "190px",
      ipAddress: "130px",
      clientName: "170px",
    },
    fields: [
      "createdAt",
      "actorName",
      "action",
      "objectType",
      "objectName",
      "ipAddress",
      "clientName",
    ],
    detailFields: [
      "createdAt",
      "actorName",
      "action",
      "objectType",
      "objectName",
      "ipAddress",
      "clientName",
      "actorId",
      "objectId",
      "beforeValue",
      "afterValue",
      "userAgent",
    ],
    labels: {
      createdAt: "时间",
      actorName: "操作人",
      action: "操作",
      objectType: "对象类型",
      objectName: "对象名称",
      ipAddress: "来源 IP",
      clientName: "客户端",
      actorId: "操作人内部 ID",
      objectId: "对象内部 ID",
      beforeValue: "变更前",
      afterValue: "变更后",
      userAgent: "完整客户端标识",
    },
    fieldOptions: {
      action: opts([
        ["供应商价格同步完成", "PROVIDER_PRICE_SYNC_COMPLETE"],
        ["供应商连接测试", "TEST_CONNECTION"],
        ["验证模型候选", "MODEL_DISCOVERY_CANDIDATE_VERIFY"],
        ["创建价格同步任务", "PROVIDER_PRICE_SYNC_CREATE"],
        ["模型能力真实探测", "CAPABILITY_LIVE_PROBE"],
        ["发现供应商模型", "PROVIDER_MODEL_DISCOVERY"],
        ["模型部署探测通过", "MODEL_DEPLOYMENT_PROBE_PASSED"],
        ["模型部署探测失败", "MODEL_DEPLOYMENT_PROBE_FAILED"],
        ["官方价格自动匹配", "PROVIDER_OFFICIAL_PRICE_AUTO_MATCH"],
        ["启用价格源", "PROVIDER_PRICE_SOURCE_ENABLE"],
        ["暂停价格源", "PROVIDER_PRICE_SOURCE_PAUSE"],
        ["更新价格源", "PROVIDER_PRICE_SOURCE_UPDATE"],
        ["批准价格差异", "PROVIDER_PRICE_DIFF_APPROVE"],
        ["发布供应商价格", "PROVIDER_PRICE_PUBLISH"],
        ["创建官方价格目录", "PROVIDER_PRICE_CATALOG_CREATE"],
        ["修订官方价格目录", "PROVIDER_PRICE_CATALOG_REVISE"],
        ["创建路由策略", "ROUTE_CREATE"],
        ["更新路由策略", "ROUTE_UPDATE"],
        ["生效路由策略", "ROUTE_ACTIVATE"],
        ["退役路由策略", "ROUTE_RETIRE"],
        ["自动批准模型部署", "MODEL_DEPLOYMENT_AUTO_APPROVE"],
        ["发现模型部署", "MODEL_DEPLOYMENT_DISCOVERED"],
        ["批准模型进入生产", "MODEL_DEPLOYMENT_PRODUCTION_APPROVE"],
        ["暂停生产模型", "MODEL_DEPLOYMENT_PRODUCTION_SUSPEND"],
        ["批准模型别名", "PROVIDER_MODEL_ALIAS_APPROVE"],
        ["托管或轮换供应商密钥", "PROVIDER_SECRET_ROTATE"],
        ["创建租户", "TENANT_CREATE"],
        ["更新租户", "TENANT_UPDATE"],
        ["启用租户", "TENANT_ACTIVATE"],
        ["收回租户模型授权", "TENANT_MODEL_ACCESS_REVOKED"],
        ["变更租户状态", "TENANT_STATE_CHANGE"],
        ["创建项目", "PROJECT_CREATE"],
        ["变更项目状态", "PROJECT_STATE_CHANGE"],
        ["创建应用", "APP_CREATE"],
        ["更新应用", "APP_UPDATE"],
        ["变更应用状态", "APP_STATE_CHANGE"],
        ["创建 API Key", "CREATE_KEY"],
        ["生成 API Key", "GENERATE_KEY"],
        ["禁用 API Key", "KEY_DISABLE"],
        ["同步汇率", "FX_RATE_SYNC"],
        ["人工维护汇率", "FX_RATE_MANUAL_OVERRIDE"],
        ["恢复自动汇率", "FX_RATE_RESTORE_AUTO"],
        ["创建账户", "USER_ACCOUNT_CREATE"],
        ["更新系统配置", "UPDATE_CONFIGURATION"],
        ["变更状态", "STATE_CHANGE"],
        ["创建", "CREATE"],
        ["发布", "PUBLISH"],
      ]),
      objectType: opts([
        ["价格同步任务", "ProviderPriceSyncRun"],
        ["供应商渠道", "ProviderInstance"],
        ["模型部署", "ChannelModelDeployment"],
        ["模型候选", "ModelDiscoveryCandidate"],
        ["能力验证", "CapabilityValidation"],
        ["价格源", "ProviderPriceSource"],
        ["供应商官方价格", "ProviderModelPriceCatalog"],
        ["价格差异", "ProviderPriceDiff"],
        ["路由策略", "RoutePolicy"],
        ["API Key", "ApiKey"],
        ["企业服务模型", "PlatformModel"],
        ["租户", "Tenant"],
        ["应用", "App"],
        ["项目", "Project"],
        ["汇率", "FxRate"],
        ["汇率同步任务", "FxRateSyncRun"],
        ["供应商密钥", "ProviderSecret"],
        ["模型别名", "ProviderModelAlias"],
        ["用户账户", "UserAccount"],
      ]),
    },
  },
  sensitiveAccess: {
    title: "敏感查看记录",
    desc: "记录敏感数据查看的理由、审批与访问结果。",
    apiPath: "/api/audit/sensitive-access",
    readonly: true,
    fields: [
      "actorId",
      "objectType",
      "objectId",
      "reason",
      "fieldsViewed",
      "createdAt",
    ],
    labels: {
      actorId: "查看人",
      objectType: "资源类型",
      objectId: "资源 ID",
      reason: "查看理由",
      fieldsViewed: "查看字段",
      createdAt: "时间",
    },
  },
  providerBillingSources: {
    title: "供应商账单源",
    desc: "通过供应商 Costs/账单 API 同步实际扣费，用于校准 TokenSea 实时估算成本；账单数据不会直接改写模型价格。",
    apiPath: "/api/provider-billing-sources",
    defaultSort: "createdAt",
    defaultOrder: "desc",
    fields: [
      "name",
      "providerInstanceName",
      "adapterCode",
      "defaultCurrency",
      "scheduleExpression",
      "syncRunCount",
      "billingRecordCount",
      "lastSuccessAt",
      "lastError",
      "status",
    ],
    detailFields: [
      "name",
      "providerInstanceName",
      "providerInstanceId",
      "adapterCode",
      "endpoint",
      "officialHosts",
      "defaultCurrency",
      "scheduleExpression",
      "config",
      "status",
      "nextRunAt",
      "lastSuccessAt",
      "lastFailureAt",
      "lastError",
      "createdAt",
      "updatedAt",
    ],
    labels: {
      name: "账单源名称",
      providerInstanceId: "供应商渠道",
      providerInstanceName: "供应商渠道",
      providerType: "供应商类型",
      adapterCode: "账单适配器",
      endpoint: "账单 API 地址",
      officialHosts: "官方域名",
      defaultCurrency: "默认币种",
      scheduleExpression: "同步周期",
      config: "账单适配器配置",
      syncRunCount: "同步次数",
      billingRecordCount: "账单记录",
      status: "状态",
      nextRunAt: "下次同步",
      lastSuccessAt: "最近成功",
      lastFailureAt: "最近失败",
      lastError: "最近错误",
      createdAt: "创建时间",
      updatedAt: "更新时间",
    },
    requiredFields: [
      "name",
      "providerInstanceId",
      "adapterCode",
      "endpoint",
      "officialHosts",
      "defaultCurrency",
      "scheduleExpression",
    ],
    editableFields: [
      "name",
      "providerInstanceId",
      "adapterCode",
      "endpoint",
      "officialHosts",
      "defaultCurrency",
      "scheduleExpression",
      "config",
    ],
    updateMethod: "patch",
    compactForm: true,
    optionSources: {
      providerInstanceId: {
        path: "/api/provider-instances",
        label: "instanceName",
        value: "id",
      },
    },
    fieldOptions: {
      adapterCode: opts([
        ["OpenAI Costs API", "OPENAI_COSTS_API"],
        ["通用供应商账单 JSON", "GENERIC_BILLING_JSON"],
      ]),
      defaultCurrency: opts([
        ["人民币", "CNY"],
        ["美元", "USD"],
        ["欧元", "EUR"],
        ["日元", "JPY"],
      ]),
      scheduleExpression: opts([
        ["每小时", "PT1H"],
        ["每六小时", "PT6H"],
        ["每天", "P1D"],
        ["每周", "P7D"],
      ]),
      status: opts([
        ["草稿", "DRAFT"],
        ["启用", "ACTIVE"],
        ["暂停", "PAUSED"],
        ["异常", "DEGRADED"],
        ["停用", "DISABLED"],
      ]),
    },
    fieldPresets: {
      adapterCode: {
        OPENAI_COSTS_API: {
          endpoint: "https://api.openai.com/v1/organization/costs",
          officialHosts: "api.openai.com",
          defaultCurrency: "USD",
          scheduleExpression: "P1D",
          config: { lookbackDays: 7 },
        },
        GENERIC_BILLING_JSON: {
          scheduleExpression: "P1D",
          config: {
            recordsPath: "data",
            periodStartField: "period_start",
            periodEndField: "period_end",
            amountField: "amount",
            currencyField: "currency",
            inputTokensField: "input_tokens",
            outputTokensField: "output_tokens",
            requestCountField: "request_count",
            lineItemField: "line_item",
            modelField: "model",
            projectField: "project_id",
            startParam: "start_time",
            endParam: "end_time",
            timeFormat: "EPOCH_SECONDS",
            lookbackDays: 7,
          },
        },
      },
    },
    fieldTypes: {
      providerInstanceId: "select",
      adapterCode: "select",
      officialHosts: "host-list",
      defaultCurrency: "select",
      scheduleExpression: "select",
      config: "json",
      status: "select",
    },
    defaultFormValues: {
      adapterCode: "OPENAI_COSTS_API",
      endpoint: "https://api.openai.com/v1/organization/costs",
      officialHosts: "api.openai.com",
      defaultCurrency: "USD",
      scheduleExpression: "P1D",
      config: { lookbackDays: 7 },
      status: "DRAFT",
    },
    builtinActions: ["测试账单", "立即同步", "启用", "暂停"],
    builtinActionMap: {
      测试账单: "POST_SHOW :id/test",
      立即同步: ":id/sync",
      启用: ":id/enable",
      暂停: ":id/pause",
    },
    actionForms: {
      测试账单: {
        fields: ["from", "to"],
        labels: { from: "开始时间（可选）", to: "结束时间（可选）" },
        fieldTypes: { from: "datetime", to: "datetime" },
      },
      立即同步: {
        fields: ["from", "to"],
        labels: { from: "开始时间（可选）", to: "结束时间（可选）" },
        fieldTypes: { from: "datetime", to: "datetime" },
      },
    },
    relatedFields: ["httpStatus", "records", "amount", "currency", "pages", "periodStart", "periodEnd", "sample"],
    relatedLabels: {
      httpStatus: "HTTP 状态",
      records: "账单记录",
      amount: "账单金额",
      currency: "币种",
      pages: "页数",
      periodStart: "开始时间",
      periodEnd: "结束时间",
      sample: "样例",
    },
  },
  providerBillingSyncRuns: {
    title: "账单同步任务",
    desc: "查看供应商账单 API 的同步周期、抓取记录、金额及失败原因。",
    apiPath: "/api/provider-billing-sync-runs",
    readonly: true,
    defaultSort: "createdAt",
    defaultOrder: "desc",
    fields: [
      "sourceName",
      "triggerType",
      "periodStart",
      "periodEnd",
      "recordsFetched",
      "amountFetched",
      "currency",
      "status",
      "errorMessage",
      "startedAt",
      "completedAt",
      "createdAt",
    ],
    labels: {
      sourceName: "账单源",
      triggerType: "触发方式",
      periodStart: "周期开始",
      periodEnd: "周期结束",
      recordsFetched: "记录数",
      amountFetched: "金额",
      currency: "币种",
      status: "状态",
      errorMessage: "错误信息",
      startedAt: "开始时间",
      completedAt: "完成时间",
      createdAt: "创建时间",
    },
  },
  providerBillingRecords: {
    title: "供应商账单明细",
    desc: "保存供应商 Costs/账单 API 的不可变证据，并作为供应商对账的外部金额来源。",
    apiPath: "/api/provider-billing-records",
    readonly: true,
    defaultSort: "periodStart",
    defaultOrder: "desc",
    fields: [
      "sourceName",
      "providerInstanceName",
      "periodStart",
      "periodEnd",
      "lineItem",
      "providerProjectId",
      "providerModelName",
      "amount",
      "currency",
      "inputTokens",
      "outputTokens",
      "requestCount",
      "observedAt",
    ],
    detailFields: [
      "sourceName",
      "providerInstanceName",
      "periodStart",
      "periodEnd",
      "lineItem",
      "providerProjectId",
      "providerModelName",
      "amount",
      "currency",
      "inputTokens",
      "outputTokens",
      "requestCount",
      "sourceRef",
      "evidenceHash",
      "rawPayload",
      "observedAt",
      "createdAt",
    ],
    labels: {
      sourceName: "账单源",
      providerInstanceName: "供应商渠道",
      periodStart: "周期开始",
      periodEnd: "周期结束",
      lineItem: "账单项目",
      providerProjectId: "供应商项目",
      providerModelName: "供应商模型",
      amount: "金额",
      currency: "币种",
      inputTokens: "输入 Token",
      outputTokens: "输出 Token",
      requestCount: "请求数",
      sourceRef: "来源地址",
      evidenceHash: "证据哈希",
      rawPayload: "原始记录",
      observedAt: "观测时间",
      createdAt: "保存时间",
    },
  },
  reconciliations: {
    title: "供应商对账",
    desc: "录入真实供应商账单并展示与系统成本的差异。",
    apiPath: "/api/provider-reconciliations",
    fields: [
      "providerInstanceId",
      "periodStart",
      "periodEnd",
      "currency",
      "internalCost",
      "providerAmount",
      "differenceAmount",
      "tokenDifference",
      "priceDifference",
      "exchangeRateDifference",
      "taxDifference",
      "status",
      "sourceRef",
      "notes",
      "confirmedBy",
      "confirmedAt",
      "resolvedBy",
      "resolvedAt",
      "createdAt",
    ],
    labels: {
      providerInstanceId: "供应商渠道",
      periodStart: "开始日期",
      periodEnd: "结束日期",
      currency: "币种",
      internalCost: "系统成本",
      providerAmount: "供应商账单金额",
      providerTokens: "供应商 Token",
      providerExchangeRateAdjustment: "供应商汇率调整",
      providerTaxAmount: "供应商税费",
      differenceAmount: "总差异",
      tokenDifference: "Token 差异",
      priceDifference: "价格差异",
      exchangeRateDifference: "汇率差异",
      taxDifference: "税费差异",
      status: "状态",
      sourceRef: "账单依据",
      notes: "说明",
      confirmedBy: "确认人",
      confirmedAt: "确认时间",
      resolvedBy: "解决人",
      resolvedAt: "解决时间",
      createdAt: "创建时间",
    },
    requiredFields: [
      "providerInstanceId",
      "periodStart",
      "periodEnd",
      "currency",
      "providerAmount",
      "providerTokens",
      "providerExchangeRateAdjustment",
      "providerTaxAmount",
      "sourceRef",
    ],
    numberFields: [
      "providerAmount",
      "providerTokens",
      "providerExchangeRateAdjustment",
      "providerTaxAmount",
    ],
    allowEdit: false,
    editableFields: [
      "providerInstanceId",
      "periodStart",
      "periodEnd",
      "currency",
      "providerAmount",
      "providerTokens",
      "providerExchangeRateAdjustment",
      "providerTaxAmount",
      "sourceRef",
      "notes",
    ],
    optionSources: { providerInstanceId: channelSource },
    fieldOptions: { currency: opts([["人民币", "CNY"]]), status },
    fieldTypes: {
      providerInstanceId: "select",
      periodStart: "date",
      periodEnd: "date",
      currency: "select",
      notes: "textarea",
    },
    builtinActions: ["确认差异", "确认解决", "导出"],
    builtinActionMap: {
      确认差异: ":id/confirm",
      确认解决: ":id/resolve",
      导出: "DOWNLOAD :id/export",
    },
    actionForms: {
      确认解决: {
        fields: ["reason"],
        labels: { reason: "解决原因" },
        requiredFields: ["reason"],
      },
    },
  },
  approvals: {
    title: "治理审批",
    desc: "集中处理模型、价格、路由、预算等高风险变化。",
    apiPath: "/api/governance/approvals",
    readonly: true,
    fields: [
      "resourceType",
      "resourceId",
      "riskLevel",
      "reason",
      "requestedBy",
      "requestedAt",
      "decisionReason",
      "status",
    ],
    labels: {
      resourceType: "对象类型",
      resourceId: "对象 ID",
      riskLevel: "风险等级",
      reason: "变更理由",
      requestedBy: "提交人",
      requestedAt: "提交时间",
      decisionReason: "审批意见",
      status: "状态",
    },
    builtinActions: ["批准", "拒绝"],
    builtinActionMap: { 批准: ":id/approve", 拒绝: ":id/reject" },
    actionForms: {
      批准: {
        fields: ["decisionReason"],
        labels: { decisionReason: "审批意见" },
      },
      拒绝: {
        fields: ["decisionReason"],
        labels: { decisionReason: "拒绝理由" },
        requiredFields: ["decisionReason"],
      },
    },
  },
  versions: {
    title: "发布与回滚",
    desc: "查询已发布版本并回滚到可验证的稳定版本。",
    apiPath: "/api/governance/versions",
    readonly: true,
    fields: [
      "resourceType",
      "resourceId",
      "version",
      "sourceAction",
      "createdBy",
      "createdAt",
    ],
    labels: {
      resourceType: "对象类型",
      resourceId: "对象 ID",
      version: "版本",
      sourceAction: "来源动作",
      createdBy: "创建人",
      createdAt: "创建时间",
    },
    builtinActions: ["回滚"],
    builtinActionMap: { 回滚: "PATCH :id/rollback" },
  },
  errorCodes: {
    title: "错误码",
    desc: "从控制面读取当前部署支持的稳定错误码及处置建议。",
    apiPath: "/api/error-codes",
    readonly: true,
    fields: ["code", "httpStatus", "category", "message", "suggestion"],
    labels: {
      code: "错误码",
      httpStatus: "HTTP 状态",
      category: "类别",
      message: "说明",
      suggestion: "处置建议",
    },
    emptyTitle: "当前未返回错误码目录",
    emptyDescription: "请确认控制面错误码目录端点已启用。",
  },
  settings: {
    title: "系统基础设置",
    desc: "读取并维护当前部署允许变更的非敏感系统参数。",
    apiPath: "/api/system-settings",
    fields: ["group", "key", "value", "description", "sensitive", "updatedAt"],
    labels: {
      group: "设置分组",
      key: "设置键",
      value: "当前值",
      description: "设置说明",
      sensitive: "敏感设置",
      updatedAt: "更新时间",
    },
    allowCreate: false,
    editableFields: ["key", "value", "description", "sensitive"],
    updateKey: "key",
    requiredFields: ["key"],
    fieldOptions: { sensitive: yesNo },
    fieldTypes: { sensitive: "select" },
    columnWidths: {
      group: "90px",
      key: "180px",
      value: "180px",
      sensitive: "90px",
      updatedAt: "170px",
    },
    actionColumnWidth: "86px",
  },
};

export const resourceRoutes = [
  ["provider-templates", "providerTemplates"],
  ["provider-channels", "providerChannels"],
  ["model-references", "modelReferences"],
  ["model-deployments", "modelDeployments"],
  ["model-discovery-candidates", "modelDiscoveryCandidates"],
  ["provider-model-aliases", "providerModelAliases"],
  ["service-models", "serviceModels"],
  ["data-sources", "dataSources"],
  ["sync-jobs", "syncJobs"],
  ["model-discoveries", "modelDiscoveries"],
  ["discovery-diffs", "discoveryDiffs"],
  ["public-price-references", "publicPriceReferences"],
  ["provider-price-sources", "providerPriceSources"],
  ["provider-price-sync-runs", "providerPriceSyncRuns"],
  ["provider-price-snapshots", "providerPriceSnapshots"],
  ["provider-price-diffs", "providerPriceDiffs"],
  ["provider-price-catalog", "providerPriceCatalog"],
  ["price-versions", "priceVersions"],
  ["budget-rules", "budgetRules"],
  ["provider-billing-sources", "providerBillingSources"],
  ["provider-billing-sync-runs", "providerBillingSyncRuns"],
  ["provider-billing-records", "providerBillingRecords"],
  ["provider-health", "providerHealth"],
  ["alerts", "alerts"],
  ["audit", "audit"],
  ["sensitive-access", "sensitiveAccess"],
  ["provider-reconciliations", "reconciliations"],
  ["approvals", "approvals"],
  ["versions", "versions"],
  ["error-codes", "errorCodes"],
  ["system-settings", "settings"],
] as const;
