package com.tokensea.governance;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.tokensea.audit.service.AuditService;
import com.tokensea.common.ApiResponse;
import com.tokensea.security.JwtService;
import org.springframework.http.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.Authentication;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.time.OffsetDateTime;
import java.util.*;

@RestController @RequestMapping("/api")
public class AccountingController {
    private final JdbcTemplate jdbc;private final ObjectMapper json;private final AuditService audits;
    public AccountingController(JdbcTemplate jdbc,ObjectMapper json,AuditService audits){this.jdbc=jdbc;this.json=json;this.audits=audits;}
    public record StatementRequest(String tenantId,OffsetDateTime from,OffsetDateTime to,String currency){}
    public record AdjustmentRequest(BigDecimal amount,String reason){}
    public record ResolveRequest(String reason){}

    @PostMapping("/cost-statements/generate") @Transactional public ApiResponse<Map<String,Object>> generate(@RequestBody StatementRequest r){
        if(r==null||r.from()==null||r.to()==null||!r.to().isAfter(r.from()))bad("成本单周期无效");String currency=r.currency()==null?"CNY":r.currency();
        Map<String,Object> totals=jdbc.queryForMap("select count(*) request_count,coalesce(sum(prompt_tokens),0) prompt_tokens,coalesce(sum(completion_tokens),0) completion_tokens,coalesce(sum(cost_amount),0) actual_cost from usage_record where created_at>=? and created_at<? and status='SUCCESS' and (? is null or tenant_id=?) and currency=?",r.from(),r.to(),r.tenantId(),r.tenantId(),currency);
        String id=id(),number="CS-"+java.time.LocalDate.now()+"-"+id.substring(0,8).toUpperCase();jdbc.update("insert into cost_statement(id,statement_no,tenant_id,period_start,period_end,currency,request_count,prompt_tokens,completion_tokens,actual_cost) values(?,?,?,?,?,?,?,?,?,?)",id,number,r.tenantId(),r.from(),r.to(),currency,totals.get("request_count"),totals.get("prompt_tokens"),totals.get("completion_tokens"),totals.get("actual_cost"));
        jdbc.update("insert into cost_statement_line(id,statement_id,project_id,app_id,api_key_id,model_alias,provider_id,request_count,prompt_tokens,completion_tokens,actual_cost) select md5(random()::text||clock_timestamp()::text),?,project_id,app_id,api_key_id,model_alias,provider_id,count(*),coalesce(sum(prompt_tokens),0),coalesce(sum(completion_tokens),0),coalesce(sum(cost_amount),0) from usage_record where created_at>=? and created_at<? and status='SUCCESS' and (? is null or tenant_id=?) and currency=? group by project_id,app_id,api_key_id,model_alias,provider_id",id,r.from(),r.to(),r.tenantId(),r.tenantId(),currency);
        List<Map<String,Object>> anomalies=new ArrayList<>();addAnomaly(anomalies,"MISSING_PRICE",jdbc.queryForObject("select count(*) from usage_record u left join usage_cost_snapshot c on c.request_id=u.request_id where u.created_at>=? and u.created_at<? and u.status='SUCCESS' and c.id is null and (? is null or u.tenant_id=?)",Long.class,r.from(),r.to(),r.tenantId(),r.tenantId()),"存在成功调用没有成本价格快照");addAnomaly(anomalies,"RECONCILIATION_VARIANCE",jdbc.queryForObject("select count(*) from provider_reconciliation p where p.period_start<=cast(? as date) and p.period_end>=cast(? as date) and (p.difference_amount<>0 or p.token_difference<>0) and exists(select 1 from usage_record u where u.provider_id=p.provider_instance_id and u.created_at>=? and u.created_at<? and (? is null or u.tenant_id=?))",Long.class,r.to(),r.from(),r.from(),r.to(),r.tenantId(),r.tenantId()),"供应商对账存在金额或 Token 偏差");addAnomaly(anomalies,"BUDGET_EVENT",jdbc.queryForObject("select count(*) from budget_rule_event e join budget_rule b on b.id=e.rule_id where e.created_at>=? and e.created_at<? and e.action in ('BLOCK','DEGRADE') and (? is null or (b.scope_type='TENANT' and b.scope_id=?))",Long.class,r.from(),r.to(),r.tenantId(),r.tenantId()),"周期内发生预算阻断或降级");addAnomaly(anomalies,"FAILED_ATTEMPT",jdbc.queryForObject("select count(*) from request_attempt a left join usage_record u on u.request_id=a.request_id where a.created_at>=? and a.created_at<? and a.status<>'SUCCESS' and (? is null or u.tenant_id=?)",Long.class,r.from(),r.to(),r.tenantId(),r.tenantId()),"周期内存在失败的渠道调用尝试");if(!anomalies.isEmpty())jdbc.update("update cost_statement set status='ANOMALOUS',anomaly_detail=cast(? as jsonb),updated_at=now() where id=?",write(anomalies),id);
        Map<String,Object> result=one("select * from cost_statement where id=?",id);audits.record("COST_STATEMENT_GENERATE","CostStatement",id,null,result);return ApiResponse.ok(result);
    }
    @GetMapping("/cost-statements/entities") public ApiResponse<List<Map<String,Object>>> statements(@RequestParam(required=false)String tenantId,@RequestParam(required=false)String status){return ApiResponse.ok(jdbc.queryForList("select * from cost_statement where (? is null or tenant_id=?) and (? is null or status=?) order by period_start desc",tenantId,tenantId,status,status));}
    @GetMapping("/cost-statements/{id}") public ApiResponse<Map<String,Object>> statement(@PathVariable String id){Map<String,Object> result=new LinkedHashMap<>(one("select * from cost_statement where id=?",id));result.put("lines",jdbc.queryForList("select * from cost_statement_line where statement_id=? order by actual_cost desc",id));return ApiResponse.ok(result);}
    @PostMapping("/cost-statements/{id}/confirm") @Transactional public ApiResponse<Map<String,Object>> confirm(@PathVariable String id,Authentication a){return statementState(id,"GENERATED","CONFIRMED","COST_STATEMENT_CONFIRM",a);}
    @PostMapping("/cost-statements/{id}/adjust") @Transactional public ApiResponse<Map<String,Object>> adjust(@PathVariable String id,@RequestBody AdjustmentRequest r,Authentication a){if(r==null||r.amount()==null||r.reason()==null||r.reason().isBlank())bad("调整金额和原因不能为空");Map<String,Object> before=one("select * from cost_statement where id=?",id);jdbc.update("update cost_statement set adjustment_amount=?,status='ADJUSTED',anomaly_detail=jsonb_build_object('adjustmentReason',?),updated_at=now() where id=?",r.amount(),r.reason(),id);return audited("COST_STATEMENT_ADJUST",id,before,a);}
    @GetMapping(value="/cost-statements/{id}/export",produces="text/csv") @Transactional public ResponseEntity<byte[]> exportStatement(@PathVariable String id,Authentication a){Map<String,Object>s=one("select * from cost_statement where id=?",id);List<Map<String,Object>>lines=jdbc.queryForList("select project_id,app_id,api_key_id,model_alias,provider_id,request_count,prompt_tokens,completion_tokens,actual_cost from cost_statement_line where statement_id=? order by actual_cost desc",id);StringBuilder csv=new StringBuilder("project_id,app_id,api_key_id,model_alias,provider_id,request_count,prompt_tokens,completion_tokens,actual_cost\n");for(Map<String,Object>line:lines)csv.append(line.values().stream().map(AccountingController::csv).reduce((x,y)->x+","+y).orElse("")).append('\n');jdbc.update("update cost_statement set status='EXPORTED',exported_at=now(),updated_at=now() where id=?",id);audits.record("COST_STATEMENT_EXPORT","CostStatement",id,s,Map.of("rows",lines.size(),"actor",actor(a)));return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=cost-statement-"+id+".csv").body(csv.toString().getBytes(StandardCharsets.UTF_8));}

    @PostMapping("/provider-reconciliations/{id}/confirm") @Transactional public ApiResponse<Map<String,Object>> confirmReconciliation(@PathVariable String id,Authentication a){Map<String,Object>before=one("select * from provider_reconciliation where id=?",id);jdbc.update("update provider_reconciliation set confirmed_by=?,confirmed_at=now(),status=case when difference_amount=0 then 'MATCHED' else 'DISPUTED' end,updated_at=now() where id=?",actor(a),id);return reconciled("PROVIDER_RECONCILIATION_CONFIRM",id,before);}
    @PostMapping("/provider-reconciliations/{id}/resolve") @Transactional public ApiResponse<Map<String,Object>> resolveReconciliation(@PathVariable String id,@RequestBody ResolveRequest r,Authentication a){if(r==null||r.reason()==null||r.reason().isBlank())bad("解决原因不能为空");Map<String,Object>before=one("select * from provider_reconciliation where id=?",id);jdbc.update("update provider_reconciliation set status='RESOLVED',resolved_by=?,resolved_at=now(),notes=concat_ws(E'\\n',notes,?),updated_at=now() where id=?",actor(a),r.reason(),id);return reconciled("PROVIDER_RECONCILIATION_RESOLVE",id,before);}
    @GetMapping(value="/provider-reconciliations/{id}/export",produces="application/json") public ResponseEntity<byte[]> exportReconciliation(@PathVariable String id){try{return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=reconciliation-"+id+".json").body(json.writeValueAsBytes(one("select * from provider_reconciliation where id=?",id)));}catch(Exception e){throw new IllegalStateException(e);}}

    private ApiResponse<Map<String,Object>> statementState(String id,String expected,String target,String action,Authentication a){Map<String,Object>before=one("select * from cost_statement where id=?",id);if(!expected.equals(before.get("status")))throw new ResponseStatusException(HttpStatus.CONFLICT,"成本单状态不允许该操作");jdbc.update("update cost_statement set status=?,confirmed_by=?,confirmed_at=now(),updated_at=now() where id=?",target,actor(a),id);return audited(action,id,before,a);}
    private ApiResponse<Map<String,Object>> audited(String action,String id,Map<String,Object>before,Authentication a){Map<String,Object>after=one("select * from cost_statement where id=?",id);audits.record(action,"CostStatement",id,before,Map.of("value",after,"actor",actor(a)));return ApiResponse.ok(after);}
    private ApiResponse<Map<String,Object>> reconciled(String action,String id,Map<String,Object>before){Map<String,Object>after=one("select * from provider_reconciliation where id=?",id);audits.record(action,"ProviderReconciliation",id,before,after);return ApiResponse.ok(after);}
    private void addAnomaly(List<Map<String,Object>> target,String code,Long count,String reason){if(count!=null&&count>0)target.add(Map.of("code",code,"count",count,"reason",reason));}private String write(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException(e);}}
    private Map<String,Object>one(String sql,Object...args){List<Map<String,Object>>rows=jdbc.queryForList(sql,args);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"记录不存在");return rows.get(0);}private static String actor(Authentication a){return a!=null&&a.getPrincipal() instanceof JwtService.Identity i?i.userId():"SYSTEM";}private static void bad(String m){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}private static String id(){return UUID.randomUUID().toString().replace("-","");}private static String csv(Object value){String s=value==null?"":String.valueOf(value);return"\""+s.replace("\"","\"\"")+"\"";}
}
