package com.tokensea.governance;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.tokensea.audit.service.AuditService;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import java.util.*;

@Service
public class GovernanceApprovalService {
    private final JdbcTemplate jdbc;private final ObjectMapper json;private final AuditService audits;
    public GovernanceApprovalService(JdbcTemplate jdbc,ObjectMapper json,AuditService audits){this.jdbc=jdbc;this.json=json;this.audits=audits;}
    @Transactional public Map<String,Object> submit(String type,String resourceId,String reason,String actor){String table=table(type);Map<String,Object> snapshot=one("select * from "+table+" where id=?",resourceId);Integer version=jdbc.queryForObject("select coalesce(max(version),0)+1 from governance_version where resource_type=? and resource_id=?",Integer.class,type,resourceId);String versionId=id(),approvalId=id();jdbc.update("insert into governance_version(id,resource_type,resource_id,version,snapshot,source_action,created_by) values(?,?,?,?,cast(? as jsonb),'SUBMIT',?)",versionId,type,resourceId,version,write(snapshot),actor);jdbc.update("insert into approval_request(id,resource_type,resource_id,version_id,risk_level,reason,requested_by) values(?,?,?,?, 'HIGH',?,?)",approvalId,type,resourceId,versionId,reason,actor);Map<String,Object> result=one("select * from approval_request where id=?",approvalId);audits.record("GOVERNANCE_SUBMIT","ApprovalRequest",approvalId,null,result);return result;}
    @Transactional public void requireApproved(String type,String resourceId,String actor){List<Map<String,Object>> rows=jdbc.queryForList("select * from approval_request where resource_type=? and resource_id=? and status='APPROVED' order by decided_at desc limit 1",type,resourceId);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.CONFLICT,"高风险变更尚未审批通过");jdbc.update("update approval_request set status='EXECUTED',decided_by=coalesce(decided_by,?),decided_at=coalesce(decided_at,now()) where id=?",actor,rows.get(0).get("id"));}
    @Transactional public Map<String,Object> rollback(String versionId,String actor){Map<String,Object> version=one("select * from governance_version where id=?",versionId);String type=String.valueOf(version.get("resource_type")),resource=String.valueOf(version.get("resource_id")),table=table(type);Map<String,Object> before=one("select * from "+table+" where id=?",resource),snapshot=read(version.get("snapshot"));restore(type,resource,snapshot);Map<String,Object> after=one("select * from "+table+" where id=?",resource);audits.record("GOVERNANCE_ROLLBACK",type,resource,before,Map.of("restoredVersionId",versionId,"value",after,"actor",actor));return after;}
    private void restore(String type,String id,Map<String,Object>s){switch(type){case"PLATFORM_MODEL"->jdbc.update("update platform_model set platform_model_name=?,display_name=?,model_template_ids=?,provider_instance_ids=?,actual_models=?,route_policy_id=?,route_policy=?,price_policy_id=?,price_policy=?,visibility_scope=?,approval_required=?,status=?,updated_at=now() where id=?",s.get("platform_model_name"),s.get("display_name"),s.get("model_template_ids"),s.get("provider_instance_ids"),s.get("actual_models"),s.get("route_policy_id"),s.get("route_policy"),s.get("price_policy_id"),s.get("price_policy"),s.get("visibility_scope"),s.get("approval_required"),s.get("status"),id);case"ROUTE_POLICY"->jdbc.update("update route_policy set name=?,model_alias=?,strategy=?,fallback_enabled=?,config=?,status=?,updated_at=now() where id=?",s.get("name"),s.get("model_alias"),s.get("strategy"),s.get("fallback_enabled"),s.get("config"),s.get("status"),id);case"MODEL_PRICE"->jdbc.update("update model_price set platform_model_id=?,provider_instance_id=?,currency=?,input_cost_per_1k=?,output_cost_per_1k=?,input_price_per_1k=?,output_price_per_1k=?,effective_from=?,effective_to=?,status=?,updated_at=now() where id=?",s.get("platform_model_id"),s.get("provider_instance_id"),s.get("currency"),s.get("input_cost_per_1k"),s.get("output_cost_per_1k"),s.get("input_price_per_1k"),s.get("output_price_per_1k"),s.get("effective_from"),s.get("effective_to"),s.get("status"),id);case"PRICE_VERSION"->jdbc.update("update price_version set price_layer=?,public_model_reference_id=?,deployment_id=?,platform_model_id=?,currency=?,input_amount_per_1k=?,output_amount_per_1k=?,source_type=?,source_ref=?,source_confidence=?,effective_from=?,effective_to=?,status=?,updated_at=now() where id=?",s.get("price_layer"),s.get("public_model_reference_id"),s.get("deployment_id"),s.get("platform_model_id"),s.get("currency"),s.get("input_amount_per_1k"),s.get("output_amount_per_1k"),s.get("source_type"),s.get("source_ref"),s.get("source_confidence"),s.get("effective_from"),s.get("effective_to"),s.get("status"),id);case"BUDGET_RULE"->jdbc.update("update budget_rule set scope_type=?,scope_id=?,currency=?,amount_limit=?,warning_threshold_percent=?,over_limit_action=?,degrade_model_alias=?,status=?,approval_status=?,effective_from=?,effective_to=?,updated_at=now() where id=?",s.get("scope_type"),s.get("scope_id"),s.get("currency"),s.get("amount_limit"),s.get("warning_threshold_percent"),s.get("over_limit_action"),s.get("degrade_model_alias"),s.get("status"),s.get("approval_status"),s.get("effective_from"),s.get("effective_to"),id);default->throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"资源类型不支持回滚");}}
    private static String table(String type){return switch(type){case"PLATFORM_MODEL"->"platform_model";case"ROUTE_POLICY"->"route_policy";case"MODEL_PRICE"->"model_price";case"PRICE_VERSION"->"price_version";case"BUDGET_RULE"->"budget_rule";default->throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"资源类型无效");};}
    private Map<String,Object> one(String sql,Object...args){List<Map<String,Object>>r=jdbc.queryForList(sql,args);if(r.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"治理资源不存在");return r.get(0);}private String write(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw new IllegalStateException(e);}}private Map<String,Object>read(Object v){try{return json.readValue(String.valueOf(v),new TypeReference<>(){});}catch(Exception e){throw new IllegalStateException(e);}}private static String id(){return UUID.randomUUID().toString().replace("-","");}
}
