-- Repair historical usage records that were committed before their immutable cost snapshot.
-- This migration is idempotent and preserves the price version captured on usage_record.
INSERT INTO usage_cost_snapshot(
    id,
    request_id,
    usage_record_id,
    price_version_id,
    price_layer,
    currency,
    billing_basis,
    billing_quantity,
    input_unit_price,
    cache_read_unit_price,
    cache_read_mode,
    cache_write_unit_price,
    cache_write_mode,
    output_unit_price,
    prompt_tokens,
    completion_tokens,
    actual_cost_amount,
    source_ref,
    created_at,
    cache_read_tokens,
    cache_write_tokens,
    reasoning_tokens,
    price_components,
    cost_components,
    pricing_model,
    response_model,
    provider_instance_id,
    model_deployment_id,
    calculator_version,
    evidence_hash,
    input_uncached_tokens,
    input_tokens_total,
    output_tokens,
    cache_storage_token_seconds,
    usage_schema_version,
    usage_source,
    usage_evidence,
    cache_gross_savings,
    cache_write_premium,
    cache_storage_cost,
    cache_net_savings,
    cache_hit_rate,
    cost_status
)
SELECT
    md5('cost:' || u.request_id),
    u.request_id,
    u.id,
    u.price_version_id,
    coalesce(p.price_layer, 'PROVIDER_OFFICIAL'),
    upper(substring(u.currency from 1 for 3)),
    coalesce(p.billing_basis, 'TOKEN'),
    coalesce(p.billing_quantity, 1000000),
    coalesce(p.input_unit_price, 0),
    p.cache_read_unit_price,
    coalesce(p.cache_read_mode, 'UNKNOWN'),
    p.cache_write_unit_price,
    coalesce(p.cache_write_mode, 'UNKNOWN'),
    coalesce(p.output_unit_price, 0),
    u.prompt_tokens,
    u.completion_tokens,
    u.cost_amount,
    coalesce(p.source_ref, 'historical usage_record backfill'),
    u.created_at,
    0,
    0,
    0,
    coalesce(p.price_components, '[]'::jsonb),
    jsonb_build_array(jsonb_build_object(
        'componentType', 'HISTORICAL_TOTAL',
        'amount', u.cost_amount::text,
        'currency', u.currency,
        'source', 'USAGE_RECORD_BACKFILL'
    )),
    u.runtime_model_name,
    null,
    u.provider_id,
    p.deployment_id,
    'historical-backfill-1.0',
    p.evidence_hash,
    u.prompt_tokens,
    u.prompt_tokens,
    u.completion_tokens,
    0,
    2,
    'HISTORICAL_USAGE_RECORD',
    jsonb_build_object(
        'requestId', u.request_id,
        'reason', 'missing immutable cost snapshot repaired from usage_record and captured price_version'
    ),
    0,
    0,
    0,
    0,
    0,
    case when p.id is null then 'INCOMPLETE_PRICE' else 'COMPLETE' end
FROM usage_record u
LEFT JOIN price_version p ON p.id = u.price_version_id
WHERE NOT EXISTS (
    SELECT 1 FROM usage_cost_snapshot cs WHERE cs.request_id = u.request_id
)
ON CONFLICT(request_id) DO NOTHING;
